# Generated by Django 3.2.5 on 2021-08-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.FileField(upload_to='cypress/uploaded_codes')),
                ('downloaded', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='purchasedcodes',
            name='data',
            field=models.FileField(upload_to='cypress/purchased_codes'),
        ),
        migrations.AlterField(
            model_name='refundedcodes',
            name='data',
            field=models.FileField(upload_to='cypress/refunded_codes'),
        ),
    ]
