# Generated by Django 3.2.5 on 2021-08-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsumo', '0002_auto_20210824_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsumocode',
            old_name='bought_before',
            new_name='purchased_before',
        ),
    ]
