# Generated by Django 3.2.5 on 2021-08-24 23:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_team_override_row_limit'),
        ('appsumo', '0003_rename_bought_before_appsumocode_purchased_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsumoReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('review_link', models.URLField(unique=True, validators=[django.core.validators.RegexValidator('^https:\\/\\/appsumo\\.com\\/products\\/marketplace-gyana\\/\\#r[0-9]{6,9}$', 'Paste the exact link as displayed on AppSumo')])),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
