# Generated by Django 3.2.6 on 2021-08-27 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumo', '0004_appsumoreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsumoreview',
            name='review_link',
            field=models.URLField(error_messages={'unique': "A user has linked to this review for their team. If you think this is a mistake, reach out to support and we'll sort it out for you."}, unique=True, validators=[django.core.validators.RegexValidator('^https:\\/\\/appsumo\\.com\\/products\\/marketplace-gyana\\/\\#r[0-9]{6,9}$', 'Paste the exact link as displayed on AppSumo')]),
        ),
    ]
