# Generated by Django 3.2.6 on 2021-09-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appsumo", "0005_alter_appsumoreview_review_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appsumocode",
            name="purchased_before",
        ),
        migrations.RemoveField(
            model_name="purchasedcodes",
            name="downloaded",
        ),
        migrations.RemoveField(
            model_name="uploadedcodes",
            name="downloaded",
        ),
        migrations.AddField(
            model_name="appsumocode",
            name="deal",
            field=models.CharField(
                choices=[
                    ("usd_49", "Launch deal $49 (Apr-June)"),
                    ("usd_179", "Temporary raise to $179 (1 week in June)"),
                    ("usd_59", "Final Marketplace $59 (July-Aug)"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchasedcodes",
            name="deal",
            field=models.CharField(
                choices=[
                    ("usd_49", "Launch deal $49 (Apr-June)"),
                    ("usd_179", "Temporary raise to $179 (1 week in June)"),
                    ("usd_59", "Final Marketplace $59 (July-Aug)"),
                ],
                default="usd_59",
                max_length=8,
            ),
            preserve_default=False,
        ),
    ]
