# Generated by Django 3.2.6 on 2021-09-02 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_team_override_row_limit'),
        ('appsumo', '0006_auto_20210902_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsumocode',
            name='deal',
            field=models.CharField(choices=[('usd_49', 'Launch deal $49 (24/03/21 - 25/06/21)'), ('usd_179', 'Temporary deal $179 (25/06/21 - 01/07/21)'), ('usd_59', 'Final deal $59 (01/07/21 - 26/08/21)')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedcodes',
            name='deal',
            field=models.CharField(choices=[('usd_49', 'Launch deal $49 (24/03/21 - 25/06/21)'), ('usd_179', 'Temporary deal $179 (25/06/21 - 01/07/21)'), ('usd_59', 'Final deal $59 (01/07/21 - 26/08/21)')], max_length=8),
        ),
        migrations.CreateModel(
            name='AppsumoExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rows', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
