# Generated by Django 3.2.6 on 2021-09-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsumo', '0007_auto_20210902_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsumocode',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='appsumoextra',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='appsumoreview',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='purchasedcodes',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='refundedcodes',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='uploadedcodes',
            options={'ordering': ('-updated',)},
        ),
    ]
