# Generated by Django 3.2.7 on 2021-10-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsumo', '0008_alter_appsumoreview_review_link'),
        ('appsumo', '0008_auto_20210921_2100'),
    ]

    operations = [
    ]
