# Generated by Django 3.2.7 on 2021-10-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumo', '0009_merge_20211001_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsumocode',
            name='deal',
            field=models.CharField(choices=[('usd_49', 'Launch deal $49 (24/03/21 - 25/06/21)'), ('usd_179', 'Temporary deal $179 (25/06/21 - 01/07/21)'), ('usd_59', 'Final deal $59 (01/07/21 - 26/08/21)'), ('select', 'AppSumo Select (28/10/21 -)')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedcodes',
            name='deal',
            field=models.CharField(choices=[('usd_49', 'Launch deal $49 (24/03/21 - 25/06/21)'), ('usd_179', 'Temporary deal $179 (25/06/21 - 01/07/21)'), ('usd_59', 'Final deal $59 (01/07/21 - 26/08/21)'), ('select', 'AppSumo Select (28/10/21 -)')], max_length=8),
        ),
    ]
