# Generated by Django 4.0.8 on 2022-12-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsumo', '0010_auto_20211004_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsumocode',
            name='redeemed_by',
        ),
        migrations.RemoveField(
            model_name='appsumocode',
            name='team',
        ),
        migrations.RemoveField(
            model_name='appsumoextra',
            name='team',
        ),
        migrations.RemoveField(
            model_name='appsumoreview',
            name='team',
        ),
        migrations.DeleteModel(
            name='PurchasedCodes',
        ),
        migrations.DeleteModel(
            name='RefundedCodes',
        ),
        migrations.DeleteModel(
            name='UploadedCodes',
        ),
        migrations.DeleteModel(
            name='AppsumoCode',
        ),
        migrations.DeleteModel(
            name='AppsumoExtra',
        ),
        migrations.DeleteModel(
            name='AppsumoReview',
        ),
    ]
