# Generated by Django 3.2.5 on 2021-08-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_description"),
        ("sheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheet",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE sheets_sheet
            SET project_id = integrations_integration.project_id
            FROM integrations_integration
            WHERE sheets_sheet.integration_id = integrations_integration.id
            """
        ),
        migrations.AlterField(
            model_name="sheet",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
    ]
