# Generated by Django 3.2.5 on 2021-08-08 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_auto_20210808_1020'),
        ('sheets', '0002_sheet_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='integration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.integration'),
        ),
    ]
