# Generated by Django 3.2.5 on 2021-08-08 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheets', '0003_alter_sheet_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='has_initial_sync',
        ),
        migrations.AddField(
            model_name='sheet',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
