# Generated by Django 3.2.5 on 2021-08-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20210808_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='drive_file_last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
