# Generated by Django 3.2.5 on 2021-08-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0005_sheet_drive_file_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheet",
            name="external_table_sync_started",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL(
            """
        UPDATE sheets_sheet
        SET external_table_sync_started = created
        """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
