# Generated by Django 3.2.5 on 2021-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_sheet_external_table_sync_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='sheet_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
