# Generated by Django 3.2.6 on 2021-09-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_alter_sheet_integration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheet',
            options={'ordering': ('-updated',)},
        ),
    ]
