# Generated by Django 3.2.7 on 2021-11-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_alter_sheet_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='drive_file_last_modified',
            new_name='drive_file_last_modified_at_sync',
        ),
        migrations.AddField(
            model_name='sheet',
            name='drive_modified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
