# Generated by Django 3.2.7 on 2021-12-02 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0013_auto_20211119_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='next_daily_sync',
        ),
    ]
