# Generated by Django 3.2.7 on 2021-12-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0014_remove_sheet_next_daily_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheet",
            name="sheet_name",
            field=models.CharField(
                blank=True,
                help_text="Select a specific sheet by submitting the tab name",
                max_length=50,
                null=True,
                verbose_name="Sheet selection",
            ),
        ),
        migrations.AlterField(
            model_name="sheet",
            name="cell_range",
            field=models.CharField(
                blank=True,
                help_text="Select a range of cells e.g. A2:D14",
                max_length=64,
                null=True,
            ),
        ),
        migrations.RunSQL(
            """
UPDATE sheets_sheet
    SET sheet_name = CASE
        WHEN cell_range ILIKE '%!%' THEN split_part(cell_range,'!', 1)
        WHEN cell_range ILIKE '%:%'
            THEN null
        ELSE cell_range
    END, 
    cell_range = CASE
        WHEN  cell_range ilike '%!%' 
            THEN split_part( cell_range,'!', 2)
        WHEN cell_range ilike '%:%'
            THEN cell_range
        ELSE null
    END 
WHERE cell_range is not null;""",
            reverse_sql="""
UPDATE sheets_sheet
SET cell_range = CASE
    WHEN sheet_name is not null and cell_range is not null
        THEN sheet_name || '!' || cell_range
    ELSE COALESCE(sheet_name, cell_range)
    END
""",
        ),
    ]
