# Generated by Django 3.2.7 on 2021-12-07 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0015_auto_20211207_1150"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sheet",
            name="sync_started",
        ),
        migrations.RemoveField(
            model_name="sheet",
            name="sync_task_id",
        ),
    ]
