# Generated by Django 3.2.7 on 2021-12-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0016_auto_20211207_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='failed_at',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='succeeded_at',
        ),
    ]
