# Generated by Django 3.2.7 on 2021-12-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sheets", "0017_auto_20211214_0052"),
        ("integrations", "0026_auto_20211221_0106"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sheet",
            name="is_scheduled",
        ),
    ]
