# Generated by Django 4.0.8 on 2023-02-02 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        ('workflows', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='credit_confirmed_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='input_table',
            field=models.ForeignKey(help_text='Select a table from an integration or workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_nodes', to='tables.table'),
        ),
        migrations.AddField(
            model_name='node',
            name='parents',
            field=models.ManyToManyField(blank=True, through='nodes.Edge', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='edge',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edges', to='nodes.node'),
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('child', 'position')},
        ),
    ]
