# Generated by Django 3.2 on 2021-07-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("nodes", "0001_initial"), ("workflows", "0043_auto_20210713_2233")]
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="column",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="editcolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="formulacolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="renamecolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="secondarycolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="sortcolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="windowcolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="AddColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(name="AddColumn", table="columns_addcolumn")
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Column",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(name="Column", table="columns_column")
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="EditColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="EditColumn", table="columns_editcolumn"
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="FormulaColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="FormulaColumn", table="columns_formulacolumn"
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="FunctionColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="FunctionColumn", table="columns_functioncolumn"
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="RenameColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="RenameColumn", table="columns_renamecolumn"
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="SecondaryColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="SecondaryColumn", table="columns_secondarycolumn"
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="SortColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="SortColumn", table="columns_sortcolumn"
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="WindowColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="WindowColumn", table="columns_windowcolumn"
                )
            ],
        ),
    ]
