# Generated by Django 4.0.8 on 2023-03-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='always_use_credits',
        ),
        migrations.RemoveField(
            model_name='node',
            name='credit_confirmed_user',
        ),
        migrations.RemoveField(
            model_name='node',
            name='credit_use_confirmed',
        ),
        migrations.RemoveField(
            model_name='node',
            name='uses_credits',
        ),
    ]
