# Generated by Django 3.2.5 on 2021-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_alter_node_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='limit_offset',
            field=models.IntegerField(blank=True, help_text='From where to start the limit', null=True),
        ),
    ]
