# Generated by Django 3.2.5 on 2021-08-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0004_alter_node_limit_offset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="union_mode",
            field=models.CharField(
                choices=[("keep", "keep"), ("exclude", "exclude")],
                default="keep",
                help_text="Either keep or exclude the common rows",
                max_length=8,
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE nodes_node
            SET union_mode = 'exclude'
            WHERE union_mode = 'except'
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
