# Generated by Django 3.2.5 on 2021-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_alter_node_union_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('add', 'Add'), ('aggregation', 'Aggregation'), ('distinct', 'Distinct'), ('edit', 'Edit'), ('filter', 'Filter'), ('input', 'Get data'), ('formula', 'Formula'), ('intersect', 'Intersection'), ('join', 'Join'), ('limit', 'Limit'), ('pivot', 'Pivot'), ('output', 'Save data'), ('rename', 'Rename'), ('select', 'Select columns'), ('sort', 'Sort'), ('union', 'Union'), ('unpivot', 'Unpivot'), ('text', 'Text'), ('window', 'Window')], max_length=16),
        ),
    ]
