# Generated by Django 3.2.7 on 2021-09-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0007_auto_20210823_0705"),
    ]

    operations = [
        migrations.RunSQL(
            """
        UPDATE nodes_node
        SET name=output_name
        WHERE kind='output'""",
            reverse_sql="""UPDATE nodes_node
        SET output_name=name
        WHERE kind='output'""",
        ),
        migrations.RemoveField(
            model_name="node",
            name="output_name",
        ),
        migrations.AlterField(
            model_name="node",
            name="kind",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("aggregation", "Group and Aggregate"),
                    ("distinct", "Distinct"),
                    ("edit", "Edit"),
                    ("filter", "Filter"),
                    ("input", "Get data"),
                    ("formula", "Formula"),
                    ("intersect", "Intersect "),
                    ("join", "Join"),
                    ("limit", "Limit"),
                    ("pivot", "Pivot"),
                    ("output", "Save data"),
                    ("rename", "Rename"),
                    ("select", "Select columns"),
                    ("sort", "Sort"),
                    ("union", "Union"),
                    ("unpivot", "Unpivot"),
                    ("text", "Text"),
                    ("window", "Window and Calculate"),
                    ("sentiment", "Sentiment"),
                ],
                max_length=16,
            ),
        ),
    ]
