# Generated by Django 3.2.7 on 2021-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0008_auto_20210910_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="kind",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("aggregation", "Group and Aggregate"),
                    ("distinct", "Distinct"),
                    ("edit", "Edit"),
                    ("filter", "Filter"),
                    ("input", "Get data"),
                    ("formula", "Formula"),
                    ("intersect", "Intersect "),
                    ("join", "Join"),
                    ("limit", "Limit"),
                    ("pivot", "Pivot"),
                    ("output", "Save data"),
                    ("rename", "Rename"),
                    ("select", "Select columns"),
                    ("sort", "Sort"),
                    ("union", "Union"),
                    ("except", "Except"),
                    ("unpivot", "Unpivot"),
                    ("text", "Text"),
                    ("window", "Window and Calculate"),
                    ("sentiment", "Sentiment"),
                ],
                max_length=16,
            ),
        ),
        migrations.RunSQL(
            """
        UPDATE nodes_node
        SET kind = 'except'
        WHERE kind='union' and union_mode='exclude'
        """,
            reverse_sql="""UPDATE nodes_node
        SET kind = 'union'
            union_mode = 'exclude'
        WHERE kind='except'""",
        ),
        migrations.RemoveField(
            model_name="node",
            name="union_mode",
        ),
    ]
