# Generated by Django 3.2.7 on 2021-09-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_auto_20210910_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ()},
        ),
    ]
