# Generated by Django 3.2.7 on 2021-09-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0011_alter_node_input_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='pivot_aggregation',
            field=models.CharField(blank=True, choices=[('sum', 'Sum'), ('count', 'Count'), ('nunique', 'Count distinct'), ('mean', 'Average'), ('max', 'Maximum'), ('min', 'Minimum'), ('std', 'Standard deviation')], help_text='Select an aggregation to be applied to the new cells', max_length=20, null=True),
        ),
    ]
