# Generated by Django 3.2.7 on 2021-09-28 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_auto_20210822_0024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nodes', '0012_alter_node_pivot_aggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='always_use_credits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='cache_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_table', to='tables.table'),
        ),
        migrations.AddField(
            model_name='node',
            name='credit_confirmed_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='credit_use_confirmed',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='uses_credits',
            field=models.IntegerField(default=0),
        ),
    ]
