# Generated by Django 3.2.7 on 2021-10-25 08:01

from django.db import migrations, models


def existing_nodes_to_true(apps, schema_editor):
    Node = apps.get_model("nodes", "Node")

    for node in Node.objects.all():
        node.has_been_saved = True
        node.save()


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0013_auto_20210928_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="has_been_saved",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(existing_nodes_to_true, migrations.RunPython.noop),
    ]
