# Generated by Django 3.2.7 on 2021-11-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0015_node_parents_through_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="edge",
            options={"ordering": ("position",)},
        ),
        migrations.AlterUniqueTogether(
            name="edge",
            unique_together={("child", "position")},
        ),
    ]
