# Generated by Django 3.2.7 on 2021-11-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0016_auto_20211119_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('add', 'Add'), ('aggregation', 'Group and Aggregate'), ('convert', 'Convert'), ('distinct', 'Distinct'), ('edit', 'Edit'), ('filter', 'Filter'), ('input', 'Get data'), ('formula', 'Formula'), ('intersect', 'Intersect '), ('join', 'Join'), ('limit', 'Limit'), ('pivot', 'Pivot'), ('output', 'Save data'), ('rename', 'Rename'), ('select', 'Select columns'), ('sort', 'Sort'), ('union', 'Union'), ('except', 'Except'), ('unpivot', 'Unpivot'), ('text', 'Text'), ('window', 'Window and Calculate'), ('sentiment', 'Sentiment')], max_length=16),
        ),
    ]
