# Generated by Django 3.2.7 on 2021-11-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0017_alter_node_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_edges', to='nodes.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edges', to='nodes.node'),
        ),
    ]
