# Generated by Django 3.2.7 on 2021-11-29 00:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0018_auto_20211127_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 29, 0, 27, 40, 92986, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edge',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
