# Generated by Django 3.2.7 on 2021-12-09 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_auto_20210928_1459'),
        ('nodes', '0020_auto_20211129_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='input_table',
            field=models.ForeignKey(help_text='Select a data source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_nodes', to='tables.table'),
        ),
    ]
