# Generated by Django 3.2.11 on 2022-01-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_auto_20210928_1459'),
        ('nodes', '0021_alter_node_input_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='input_table',
            field=models.ForeignKey(help_text='Select a table from an integration or workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_nodes', to='tables.table'),
        ),
    ]
