# Generated by Django 3.2.11 on 2022-02-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0022_alter_node_input_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='cache_table',
        ),
        migrations.RemoveField(
            model_name='node',
            name='intermediate_table',
        ),
    ]
