# Generated by Django 3.2.11 on 2022-02-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0023_auto_20220208_1139"),
        ("columns", "0015_joincolumn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="join_how",
        ),
        migrations.RemoveField(
            model_name="node",
            name="join_left",
        ),
        migrations.RemoveField(
            model_name="node",
            name="join_right",
        ),
    ]
