# Generated by Django 3.2.5 on 2021-08-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20210714_1448'),
        ('widgets', '0023_delete_multivalues'),
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functioncolumn',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregations', to='widgets.widget'),
        ),
        migrations.AlterField(
            model_name='functioncolumn',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregations', to='nodes.node'),
        ),
    ]
