# Generated by Django 4.0.8 on 2023-02-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowcolumn',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window_columns', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='sortcolumn',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sort_columns', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='secondarycolumn',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_columns', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='renamecolumn',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rename_columns', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='joincolumn',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_columns', to='nodes.node'),
        ),
    ]
