# Generated by Django 3.2.5 on 2021-08-17 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0002_auto_20210802_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulacolumn',
            name='formula',
            field=models.TextField(blank=True, help_text='Type formula', null=True),
        ),
        migrations.AlterField(
            model_name='formulacolumn',
            name='label',
            field=models.CharField(help_text='New column name', max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z_][0-9a-zA-Z_]*$', 'Only numbers, letters and underscores allowed.')]),
        ),
        migrations.AlterField(
            model_name='renamecolumn',
            name='column',
            field=models.CharField(help_text='Old column name', max_length=300),
        ),
        migrations.AlterField(
            model_name='renamecolumn',
            name='new_name',
            field=models.CharField(help_text='New column name', max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z_][0-9a-zA-Z_]*$', 'Only numbers, letters and underscores allowed.')]),
        ),
        migrations.AlterField(
            model_name='sortcolumn',
            name='ascending',
            field=models.BooleanField(default=True, help_text='Ascending Sort'),
        ),
        migrations.AlterField(
            model_name='sortcolumn',
            name='column',
            field=models.CharField(help_text='Column', max_length=300),
        ),
    ]
