# Generated by Django 3.2.7 on 2021-09-14 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0004_auto_20210907_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowcolumn',
            name='column',
            field=models.CharField(help_text='Choose an aggregation column', max_length=300),
        ),
        migrations.AlterField(
            model_name='windowcolumn',
            name='function',
            field=models.CharField(choices=[('sum', 'Sum'), ('count', 'Count'), ('mean', 'Average'), ('max', 'Maximum'), ('min', 'Minimum'), ('std', 'Standard deviation')], help_text='Select an aggregation function', max_length=20),
        ),
        migrations.AlterField(
            model_name='windowcolumn',
            name='group_by',
            field=models.CharField(blank=True, help_text='Group over this column', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='windowcolumn',
            name='label',
            field=models.CharField(help_text='Select a new column name', max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z_][0-9a-zA-Z_]*$', 'Only numbers, letters and underscores allowed.')]),
        ),
        migrations.AlterField(
            model_name='windowcolumn',
            name='order_by',
            field=models.CharField(blank=True, help_text='Order by this column', max_length=300, null=True),
        ),
    ]
