# Generated by Django 3.2.7 on 2021-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0005_auto_20210914_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcolumn',
            name='float_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='integer_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='string_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='float_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='integer_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='string_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='formulacolumn',
            name='formula',
            field=models.TextField(help_text='Type formula', null=True),
        ),
    ]
