# Generated by Django 3.2.7 on 2021-09-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0006_auto_20210914_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregationcolumn',
            options={'ordering': ('created',)},
        ),
    ]
