# Generated by Django 3.2.7 on 2021-09-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0007_alter_aggregationcolumn_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregationcolumn',
            name='function',
            field=models.CharField(choices=[('sum', 'Sum'), ('count', 'Count'), ('nunique', 'Count distinct'), ('mean', 'Average'), ('max', 'Maximum'), ('min', 'Minimum'), ('std', 'Standard deviation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='windowcolumn',
            name='function',
            field=models.CharField(choices=[('sum', 'Sum'), ('count', 'Count'), ('nunique', 'Count distinct'), ('mean', 'Average'), ('max', 'Maximum'), ('min', 'Minimum'), ('std', 'Standard deviation')], help_text='Select an aggregation function', max_length=20),
        ),
    ]
