# Generated by Django 3.2.7 on 2021-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0008_auto_20210924_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcolumn',
            name='boolean_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='editcolumn',
            name='boolean_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty')], max_length=20, null=True),
        ),
    ]
