# Generated by Django 3.2.7 on 2021-11-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("columns", "0009_auto_20211111_0852"),
    ]

    operations = [
        migrations.RunSQL(
            """
UPDATE columns_formulacolumn
SET formula = 
REPLACE(
        REPLACE(
            REPLACE(
                REPLACE(
                    REPLACE(
                        REPLACE(
                            REPLACE(
                                REPLACE(
                                    REPLACE(
                                        REPLACE(
                                            REPLACE(formula, 'cast(', 'convert('), 
                                            'ceil(', 
                                            'ceiling('
                                        ),
                                        'fillna(',
                                        'fillnull('
                                    ),
                                    'strip(',
                                    'trim('
                                ),
                                'mul(',
                                'product('
                            ),
                            'pow(',
                            'power('
                        ),
                        're_extract(',
                        'regex_extract('
                    ),
                    're_search(',
                    'regex_search('
                ),
                're_replace(',
                'regex_replace('
            ),
            'strftime(',
            'format_datetime('
        ),
        'sub(',
        'subtract('
    )
""",
            reverse_sql="""
UPDATE columns_formulacolumn
SET formula =
    REPLACE(
        REPLACE(
            REPLACE(
                REPLACE(
                    REPLACE(
                        REPLACE(
                            REPLACE(
                                REPLACE(
                                    REPLACE(
                                        REPLACE(
                                            REPLACE(formula, 'convert(', 'cast('), 
                                            'ceiling(',
                                            'ceil('
                                        ),
                                        'fillnull(',
                                        'fillna('
                                    ),
                                    'trim(',
                                    'strip('
                                ),
                                'product(',
                                'mul('
                            ),
                            'power(',
                            'pow('
                        ),
                        'regex_extract(',
                        're_extract('
                    ),
                    'regex_search(',
                    're_search('
                ),
                'regex_replace(',
                're_replace('
            ),
            'format_datetime(',
            'strftime('
        ),
        'subtract(',
        'sub('
    )
""",
        )
    ]
