# Generated by Django 3.2.7 on 2021-12-13 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0041_widget_show_summary_row'),
        ('nodes', '0020_auto_20211129_0028'),
        ('columns', '0011_convertcolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='widgets.widget'),
        ),
        migrations.AlterField(
            model_name='column',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='nodes.node'),
        ),
    ]
