# Generated by Django 3.2.11 on 2022-01-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("columns", "0012_auto_20211213_0948"),
    ]

    operations = [
        migrations.RunSQL(
            """
UPDATE columns_formulacolumn
SET formula = 
REPLACE(
    REPLACE(formula, 'date(', 'extract_date('),
    'time(',
    'extract_time('
    )
""",
            reverse_sql="""
UPDATE columns_formulacolumn
SET formula =
    REPLACE(
        REPLACE(formula, 'extract_date(', 'date('),
        'extract_time(', 
        'time('
    )
""",
        )
    ]
