# Generated by Django 3.2.11 on 2022-01-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0013_rename_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='part',
            field=models.CharField(blank=True, choices=[('date', 'Date'), ('week', 'Week with year'), ('month', 'Month with year'), ('monthonly', 'Month without year'), ('year', 'Year'), ('quarter', 'Quarter with year')], help_text='Select the desired date part', max_length=16, null=True),
        ),
    ]
