# Generated by Django 3.2.11 on 2022-02-08 13:52

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models

import apps.base.clone


def forward(apps, schema_editor):
    JoinColumn = apps.get_model("columns", "JoinColumn")
    Node = apps.get_model("nodes", "Node")
    JoinColumn.objects.bulk_create(
        [
            JoinColumn(
                left_column=node.join_left,
                right_column=node.join_right,
                how=node.join_how,
                node=node,
            )
            for node in Node.objects.filter(kind="join").iterator()
        ]
    )


def backward(apps, schema_editor):
    Node = apps.get_model("nodes", "Node")
    JoinColumn = apps.get_model("columns", "JoinColumn")
    nodes = []
    for column in JoinColumn.objects.all():
        node = column.node
        node.join_left = column.left_column
        node.join_right = column.right_column
        node.join_how = column.how
        nodes.append(node)

    Node.objects.bulk_update(nodes, ["join_left", "join_right", "join_how"])


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0022_alter_node_input_table"),
        ("columns", "0014_column_part"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinColumn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "how",
                    models.CharField(
                        choices=[
                            ("inner", "Inner"),
                            ("outer", "Outer"),
                            ("left", "Left"),
                            ("right", "Right"),
                        ],
                        default="inner",
                        help_text="Select the join method, more information in the docs",
                        max_length=12,
                    ),
                ),
                ("left_index", models.IntegerField(default=0)),
                (
                    "left_column",
                    models.CharField(
                        help_text="Choose the join column from Input {}", max_length=300
                    ),
                ),
                (
                    "right_column",
                    models.CharField(
                        help_text="Choose the right join column from Input {}",
                        max_length=300,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_columns",
                        to="nodes.node",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                dirtyfields.dirtyfields.DirtyFieldsMixin,
                apps.base.clone.CloneMixin,
                models.Model,
            ),
        ),
        migrations.RunPython(forward, reverse_code=backward),
    ]
