# Generated by Django 3.2.11 on 2022-02-15 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0015_joincolumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcolumn',
            name='boolean_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='date_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('year', 'year'), ('month', 'month'), ('day', 'day')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='datetime_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('hour', 'hour'), ('minute', 'minute'), ('second', 'second'), ('millisecond', 'millisecond'), ('year', 'year'), ('month', 'month'), ('day', 'day'), ('epoch_seconds', 'epoch seconds'), ('time', 'time'), ('date', 'date')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='float_value',
            field=models.FloatField(null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='integer_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('cummax', 'cummax'), ('cummin', 'cummin'), ('abs', 'absolute value'), ('sqrt', 'square root'), ('ceil', 'ceiling'), ('floor', 'floor'), ('ln', 'ln'), ('log2', 'log2'), ('log10', 'log10'), ('log', 'log'), ('exp', 'exponent'), ('add', 'add'), ('sub', 'subtract'), ('mul', 'multiply'), ('div', 'divide')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='integer_value',
            field=models.BigIntegerField(null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='label',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z_][0-9a-zA-Z_]*$', 'Only numbers, letters and underscores allowed.')], verbose_name='New column name'),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='string_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('lower', 'to lowercase'), ('upper', 'to uppercase'), ('length', 'length'), ('reverse', 'reverse'), ('strip', 'strip'), ('lstrip', 'lstrip'), ('rstrip', 'rstrip'), ('like', 'like'), ('contains', 'contains')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='string_value',
            field=models.TextField(null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='time_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('hour', 'hour'), ('minute', 'minute'), ('second', 'second'), ('millisecond', 'millisecond')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='boolean_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='date_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('year', 'year'), ('month', 'month'), ('day', 'day')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='datetime_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('hour', 'hour'), ('minute', 'minute'), ('second', 'second'), ('millisecond', 'millisecond'), ('year', 'year'), ('month', 'month'), ('day', 'day'), ('epoch_seconds', 'epoch seconds'), ('time', 'time'), ('date', 'date')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='float_value',
            field=models.FloatField(null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='integer_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('cummax', 'cummax'), ('cummin', 'cummin'), ('abs', 'absolute value'), ('sqrt', 'square root'), ('ceil', 'ceiling'), ('floor', 'floor'), ('ln', 'ln'), ('log2', 'log2'), ('log10', 'log10'), ('log', 'log'), ('exp', 'exponent'), ('add', 'add'), ('sub', 'subtract'), ('mul', 'multiply'), ('div', 'divide')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='integer_value',
            field=models.BigIntegerField(null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='string_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('lower', 'to lowercase'), ('upper', 'to uppercase'), ('length', 'length'), ('reverse', 'reverse'), ('strip', 'strip'), ('lstrip', 'lstrip'), ('rstrip', 'rstrip'), ('like', 'like'), ('contains', 'contains')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='string_value',
            field=models.TextField(null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='time_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('hour', 'hour'), ('minute', 'minute'), ('second', 'second'), ('millisecond', 'millisecond')], max_length=20, null=True, verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='renamecolumn',
            name='column',
            field=models.CharField(max_length=300, verbose_name='Old column name'),
        ),
        migrations.AlterField(
            model_name='renamecolumn',
            name='new_name',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z_][0-9a-zA-Z_]*$', 'Only numbers, letters and underscores allowed.')], verbose_name='New column name'),
        ),
        migrations.AlterField(
            model_name='sortcolumn',
            name='column',
            field=models.CharField(max_length=300),
        ),
    ]
