# Generated by Django 3.2.11 on 2022-02-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0017_auto_20220215_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregationcolumn',
            name='rounding',
            field=models.IntegerField(default=2, help_text='Decimal point to round to'),
        ),
        migrations.AlterField(
            model_name='column',
            name='rounding',
            field=models.IntegerField(default=2, help_text='Decimal point to round to'),
        ),
    ]
