# Generated by Django 3.2.11 on 2022-02-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0018_auto_20220216_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregationcolumn',
            name='is_percentage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show in %'),
        ),
        migrations.AddField(
            model_name='column',
            name='is_percentage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show in %'),
        ),
    ]
