# Generated by Django 3.2.11 on 2022-03-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0020_historicaladdcolumn_historicalaggregationcolumn_historicalcolumn_historicalconvertcolumn_historicale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregationcolumn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='convertcolumn',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='formulacolumn',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='joincolumn',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='renamecolumn',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='secondarycolumn',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='sortcolumn',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='windowcolumn',
            options={'ordering': ('created',)},
        ),
    ]
