# Generated by Django 3.2.12 on 2022-05-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0021_auto_20220310_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortcolumn',
            options={'ordering': ('-sort_index',)},
        ),
        migrations.AddField(
            model_name='historicalsortcolumn',
            name='sort_index',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sortcolumn',
            name='sort_index',
            field=models.BigIntegerField(default=0),
        ),
    ]
