# Generated by Django 3.2.13 on 2022-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0023_auto_20220504_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregationcolumn',
            name='conditional_formatting',
            field=models.BooleanField(default=False, help_text='Select whether or not to show background color'),
        ),
        migrations.AddField(
            model_name='aggregationcolumn',
            name='negative_threshold',
            field=models.IntegerField(blank=True, default=0, help_text='Set a threshold for negative value'),
        ),
        migrations.AddField(
            model_name='aggregationcolumn',
            name='positive_threshold',
            field=models.IntegerField(blank=True, default=0, help_text='Set a threshold for positive value'),
        ),
        migrations.AddField(
            model_name='column',
            name='conditional_formatting',
            field=models.BooleanField(default=False, help_text='Select whether or not to show background color'),
        ),
        migrations.AddField(
            model_name='column',
            name='negative_threshold',
            field=models.IntegerField(blank=True, default=0, help_text='Set a threshold for negative value'),
        ),
        migrations.AddField(
            model_name='column',
            name='positive_threshold',
            field=models.IntegerField(blank=True, default=0, help_text='Set a threshold for positive value'),
        ),
        migrations.AddField(
            model_name='historicalaggregationcolumn',
            name='conditional_formatting',
            field=models.BooleanField(default=False, help_text='Select whether or not to show background color'),
        ),
        migrations.AddField(
            model_name='historicalaggregationcolumn',
            name='negative_threshold',
            field=models.IntegerField(blank=True, default=0, help_text='Set a threshold for negative value'),
        ),
        migrations.AddField(
            model_name='historicalaggregationcolumn',
            name='positive_threshold',
            field=models.IntegerField(blank=True, default=0, help_text='Set a threshold for positive value'),
        ),
        migrations.AddField(
            model_name='historicalcolumn',
            name='conditional_formatting',
            field=models.BooleanField(default=False, help_text='Select whether or not to show background color'),
        ),
        migrations.AddField(
            model_name='historicalcolumn',
            name='negative_threshold',
            field=models.IntegerField(blank=True, default=0, help_text='Set a threshold for negative value'),
        ),
        migrations.AddField(
            model_name='historicalcolumn',
            name='positive_threshold',
            field=models.IntegerField(blank=True, default=0, help_text='Set a threshold for positive value'),
        ),
    ]
