# Generated by Django 4.0.4 on 2022-06-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0024_auto_20220523_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregationcolumn',
            name='negative_threshold',
            field=models.IntegerField(default=0, help_text='Set a threshold for negative value'),
        ),
        migrations.AlterField(
            model_name='aggregationcolumn',
            name='positive_threshold',
            field=models.IntegerField(default=0, help_text='Set a threshold for positive value'),
        ),
        migrations.AlterField(
            model_name='column',
            name='negative_threshold',
            field=models.IntegerField(default=0, help_text='Set a threshold for negative value'),
        ),
        migrations.AlterField(
            model_name='column',
            name='positive_threshold',
            field=models.IntegerField(default=0, help_text='Set a threshold for positive value'),
        ),
        migrations.AlterField(
            model_name='historicalaggregationcolumn',
            name='negative_threshold',
            field=models.IntegerField(default=0, help_text='Set a threshold for negative value'),
        ),
        migrations.AlterField(
            model_name='historicalaggregationcolumn',
            name='positive_threshold',
            field=models.IntegerField(default=0, help_text='Set a threshold for positive value'),
        ),
        migrations.AlterField(
            model_name='historicalcolumn',
            name='negative_threshold',
            field=models.IntegerField(default=0, help_text='Set a threshold for negative value'),
        ),
        migrations.AlterField(
            model_name='historicalcolumn',
            name='positive_threshold',
            field=models.IntegerField(default=0, help_text='Set a threshold for positive value'),
        ),
    ]
