# Generated by Django 3.2.6 on 2021-09-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ready',
            field=models.BooleanField(default=True),
        ),
    ]
