# Generated by Django 3.2.7 on 2021-09-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210922_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='access',
            field=models.CharField(choices=[('everyone', 'Everyone in your team can access'), ('invite', 'Only invited team members can access')], default='everyone', max_length=8),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project'),
        ),
    ]
