# Generated by Django 3.2.7 on 2021-09-24 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_auto_20210924_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='invite_only_projects', through='projects.ProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
