# Generated by Django 3.2.7 on 2021-10-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnames', '0003_alter_cname_team'),
        ('projects', '0009_alter_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnames.cname'),
        ),
    ]
