# Generated by Django 3.2.7 on 2021-11-15 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_alter_project_cname"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="daily_schedule_time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
