# Generated by Django 3.2.7 on 2021-12-02 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('projects', '0012_project_daily_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='periodic_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
    ]
