# Generated by Django 4.0.8 on 2023-02-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwidget',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('metric', 'Metric'), ('table', 'Table'), ('mscolumn2d', 'Column'), ('stackedcolumn2d', 'Stacked Column'), ('msbar2d', 'Bar'), ('stackedbar2d', 'Stacked Bar'), ('msline', 'Line'), ('msline-stacked', 'Stacked Line'), ('pie2d', 'Pie'), ('msarea', 'Area'), ('doughnut2d', 'Donut'), ('scatter', 'Scatter'), ('funnel', 'Funnel'), ('radar', 'Radar'), ('bubble', 'Bubble'), ('heatmap', 'Heatmap'), ('mscombidy2d', 'Combination chart'), ('iframe', 'iframe'), ('angulargauge', 'Gauge')], default='mscolumn2d', max_length=32),
        ),
        migrations.AlterField(
            model_name='widget',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('metric', 'Metric'), ('table', 'Table'), ('mscolumn2d', 'Column'), ('stackedcolumn2d', 'Stacked Column'), ('msbar2d', 'Bar'), ('stackedbar2d', 'Stacked Bar'), ('msline', 'Line'), ('msline-stacked', 'Stacked Line'), ('pie2d', 'Pie'), ('msarea', 'Area'), ('doughnut2d', 'Donut'), ('scatter', 'Scatter'), ('funnel', 'Funnel'), ('radar', 'Radar'), ('bubble', 'Bubble'), ('heatmap', 'Heatmap'), ('mscombidy2d', 'Combination chart'), ('iframe', 'iframe'), ('angulargauge', 'Gauge')], default='mscolumn2d', max_length=32),
        ),
    ]
