# Generated by Django 3.2 on 2021-05-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='aggregator',
            field=models.CharField(choices=[('none', 'None'), ('sum', 'Sum'), ('mean', 'Average')], default='none', max_length=32),
            preserve_default=False,
        ),
    ]
