# Generated by Django 3.2 on 2021-05-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_widget_aggregator'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='visual_kind',
            field=models.CharField(choices=[('chart', 'Chart'), ('table', 'Table')], default='chart', max_length=32),
            preserve_default=False,
        ),
    ]
