# Generated by Django 3.2 on 2021-05-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_widget_visual_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='visual_kind',
        ),
        migrations.AlterField(
            model_name='widget',
            name='kind',
            field=models.CharField(choices=[('table', 'Table'), ('column2d', 'Column'), ('line', 'Line'), ('pie2d', 'Pie')], max_length=32),
        ),
    ]
