# Generated by Django 3.2 on 2021-05-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0004_auto_20210531_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
