# Generated by Django 3.2 on 2021-05-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dataflows", "0014_auto_20210507_1044"),
        ("widgets", "0005_auto_20210502_0405"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="node",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dataflows.node",
            ),
        ),
    ]
