# Generated by Django 3.2 on 2021-06-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0006_alter_widget_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='height',
            field=models.IntegerField(default=400, help_text='The height is absolute. We allow for scrollable dashboards in the y-axis.'),
        ),
        migrations.AddField(
            model_name='widget',
            name='width',
            field=models.IntegerField(default=50, help_text='The width is relative. Relative widths avoid overflow on different displays'),
        ),
        migrations.AddField(
            model_name='widget',
            name='x',
            field=models.IntegerField(default=0, help_text='The x field is relative, this avoids overflow on the x-axis in a dashboard.'),
        ),
        migrations.AddField(
            model_name='widget',
            name='y',
            field=models.IntegerField(default=0, help_text='The y field is absolute, we allow for overflow on the y-axis in a dashboard.'),
        ),
    ]
