# Generated by Django 3.2 on 2021-05-08 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20210508_0154'),
        ('widgets', '0006_widget_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='node',
        ),
        migrations.AddField(
            model_name='widget',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table'),
        ),
    ]
