# Generated by Django 3.2 on 2021-06-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0007_auto_20210609_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('table', 'Table'), ('column2d', 'Column'), ('line', 'Line'), ('pie2d', 'Pie')], default='column2d', max_length=32),
        ),
    ]
