# Generated by Django 3.2 on 2021-06-29 10:49

import django.db.models.deletion
from django.db import migrations, models
from model_clone.mixins import CloneMixin


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0010_alter_widget_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiValues",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column", models.CharField(max_length=300)),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="widgets.widget",
                    ),
                ),
            ],
            bases=(CloneMixin, models.Model),
        ),
    ]
