# Generated by Django 3.2 on 2021-06-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0011_multivalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='value',
        ),
        migrations.AlterField(
            model_name='widget',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('table', 'Table'), ('mscolumn2d', 'Column'), ('msline', 'Line'), ('pie2d', 'Pie'), ('area2d', 'Area'), ('doughnut2d', 'Donut'), ('scatter', 'Scatter'), ('funnel', 'Funnel'), ('pyramid', 'Pyramid'), ('radar', 'Radar')], default='mscolumn2d', max_length=32),
        ),
    ]
