# Generated by Django 3.2 on 2021-06-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0012_auto_20210630_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='bubble_z',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('table', 'Table'), ('mscolumn2d', 'Column'), ('msbar2d', 'Bar'), ('msline', 'Line'), ('pie2d', 'Pie'), ('area2d', 'Area'), ('doughnut2d', 'Donut'), ('scatter', 'Scatter'), ('funnel', 'Funnel'), ('pyramid', 'Pyramid'), ('radar', 'Radar'), ('bubble', 'Bubble')], default='mscolumn2d', max_length=32),
        ),
    ]
