# Generated by Django 3.2 on 2021-06-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0013_auto_20210630_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='bubble_z',
            new_name='z',
        ),
        migrations.AlterField(
            model_name='widget',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('table', 'Table'), ('mscolumn2d', 'Column'), ('msbar2d', 'Bar'), ('msline', 'Line'), ('pie2d', 'Pie'), ('area2d', 'Area'), ('doughnut2d', 'Donut'), ('scatter', 'Scatter'), ('funnel', 'Funnel'), ('pyramid', 'Pyramid'), ('radar', 'Radar'), ('bubble', 'Bubble'), ('heatmap', 'Heatmap')], default='mscolumn2d', max_length=32),
        ),
    ]
