# Generated by Django 3.2 on 2021-07-13 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0014_auto_20210630_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multivalues',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='multivalues',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multivalues',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
