# Generated by Django 3.2.5 on 2021-07-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0015_auto_20210713_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='height',
            field=models.IntegerField(default=400, help_text='The height is in absolute pixel value.'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='width',
            field=models.IntegerField(default=50, help_text='The width is in absolute pixel value.'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='x',
            field=models.IntegerField(default=0, help_text='The x field is in absolute pixel value.'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='y',
            field=models.IntegerField(default=0, help_text='The y field is in absolute pixel value.'),
        ),
    ]
