# Generated by Django 3.2.5 on 2021-07-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0016_auto_20210727_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='width',
            field=models.IntegerField(default=500, help_text='The width is in absolute pixel value.'),
        ),
    ]
