# Generated by Django 3.2.5 on 2021-07-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0018_auto_20210728_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='sort_by',
            field=models.CharField(choices=[('label', 'Label'), ('value', 'Value')], default='label', max_length=12),
        ),
    ]
