# Generated by Django 3.2.5 on 2021-07-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0019_alter_widget_sort_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('table', 'Table'), ('mscolumn2d', 'Column'), ('stackedcolumn2d', 'Stacked Column'), ('msbar2d', 'Bar'), ('stackedbar2d', 'Stacked Bar'), ('msline', 'Line'), ('pie2d', 'Pie'), ('area2d', 'Area'), ('doughnut2d', 'Donut'), ('scatter', 'Scatter'), ('funnel', 'Funnel'), ('pyramid', 'Pyramid'), ('radar', 'Radar'), ('bubble', 'Bubble'), ('heatmap', 'Heatmap')], default='mscolumn2d', max_length=32),
        ),
    ]
