# Generated by Django 3.2.5 on 2021-07-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0020_alter_widget_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='stack_100_percent',
            field=models.BooleanField(default=False),
        ),
    ]
