# Generated by Django 3.2.5 on 2021-07-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0021_widget_stack_100_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='widget',
            name='value',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
