# Generated by Django 3.2.5 on 2021-08-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0022_auto_20210730_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiValues',
        ),
    ]
