# Generated by Django 3.2.5 on 2021-08-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0023_delete_multivalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='z_aggregator',
            field=models.CharField(blank=True, choices=[('sum', 'Sum'), ('count', 'Count'), ('mean', 'Average'), ('max', 'Maximum'), ('min', 'Minimum'), ('std', 'Standard deviation')], max_length=20, null=True),
        ),
    ]
