# Generated by Django 3.2.7 on 2021-09-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0024_widget_z_aggregator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("table", "Table"),
                    ("mscolumn2d", "Column"),
                    ("stackedcolumn2d", "Stacked Column"),
                    ("msbar2d", "Bar"),
                    ("stackedbar2d", "Stacked Bar"),
                    ("msline", "Line"),
                    ("pie2d", "Pie"),
                    ("msarea", "Area"),
                    ("doughnut2d", "Donut"),
                    ("scatter", "Scatter"),
                    ("funnel", "Funnel"),
                    ("pyramid", "Pyramid"),
                    ("radar", "Radar"),
                    ("bubble", "Bubble"),
                    ("heatmap", "Heatmap"),
                ],
                default="mscolumn2d",
                max_length=32,
            ),
        ),
        migrations.RunSQL(
            """
        UPDATE widgets_widget
            SET kind = 'msarea'
        WHERE kind = 'area2d'
        """,
            reverse_sql="""
        UPDATE widgets_widget
            SET kind = 'area2d'
        WHERE kind = 'msarea'
        """,
        ),
    ]
