# Generated by Django 3.2.7 on 2021-09-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0026_auto_20210913_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='sort_by',
            field=models.CharField(choices=[('dimension', 'Dimension'), ('metric', 'Metric')], default='dimension', max_length=12),
        ),
    ]
