# Generated by Django 3.2.7 on 2021-09-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0028_alter_widget_kind"),
    ]

    operations = [
        migrations.RenameField(
            model_name="widget",
            old_name="z",
            new_name="second_dimension",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="z_aggregator",
        ),
        migrations.AlterField(
            model_name="widget",
            name="dimension",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
