# Generated by Django 3.2.7 on 2021-09-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0029_auto_20210917_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='second_dimension',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
