# Generated by Django 3.2.6 on 2021-09-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0030_alter_widget_second_dimension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ('-updated',)},
        ),
    ]
