# Generated by Django 3.2.7 on 2021-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0031_alter_widget_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='error',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
