# Generated by Django 3.2.7 on 2021-11-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0034_auto_20211104_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('metric', 'Metric'), ('table', 'Table'), ('mscolumn2d', 'Column'), ('stackedcolumn2d', 'Stacked Column'), ('msbar2d', 'Bar'), ('stackedbar2d', 'Stacked Bar'), ('msline', 'Line'), ('msline-stacked', 'Stacked Line'), ('pie2d', 'Pie'), ('msarea', 'Area'), ('doughnut2d', 'Donut'), ('scatter', 'Scatter'), ('funnel', 'Funnel'), ('pyramid', 'Pyramid'), ('radar', 'Radar'), ('bubble', 'Bubble'), ('heatmap', 'Heatmap'), ('timeseries-line', 'Line'), ('timeseries-line_stacked', 'Stacked Line'), ('timeseries-column', 'Column'), ('timeseries-column-stacked', 'Stacked Column'), ('timeseries-area', 'Area')], default='mscolumn2d', max_length=32),
        ),
    ]
