# Generated by Django 3.2.7 on 2021-12-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0037_auto_20211130_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combinationchart',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='combinationchart',
            name='on_secondary',
            field=models.BooleanField(default=False, help_text='Plot on a secondary Y-axis'),
        ),
    ]
