# Generated by Django 3.2.7 on 2021-12-10 10:19

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    """Add page of dashboard to widget"""
    Widget = apps.get_model("widgets", "Widget")
    db_alias = schema_editor.connection.alias

    for widget in Widget.objects.using(db_alias).iterator():
        widget.page = widget.dashboard.pages.first()
        widget.save()


def backward(apps, schema_editor):
    """Add dashboard of page to widget"""
    Widget = apps.get_model("widgets", "Widget")
    db_alias = schema_editor.connection.alias

    for widget in Widget.objects.using(db_alias).iterator():
        widget.dashboard = widget.page.dashboard
        widget.save()


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0017_page"),
        ("widgets", "0039_widget_date_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboards.page",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                to="dashboards.dashboard",
            ),
        ),
        migrations.RunPython(forward, reverse_code=backward),
        migrations.RemoveField(
            model_name="widget",
            name="dashboard",
        ),
        migrations.AlterField(
            model_name="widget",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to="dashboards.page",
            ),
        ),
    ]
