# Generated by Django 3.2.11 on 2022-01-10 13:21

import json
from django.db import migrations, models

def database_forwards(apps, schema_editor):
    Widget = apps.get_model("widgets", "widget")

    for widget in Widget.objects.filter(kind="text", text_content__isnull=False).all():
        widget.text_content = f'[{{"insert": {json.dumps(widget.text_content)}}}]'
        widget.save()

    return

class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0043_widget_rounding_decimal'),
    ]

    operations = [
        migrations.RunPython(database_forwards, migrations.RunPython.noop),
    ]
