# Generated by Django 3.2.11 on 2022-01-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0044_auto_20220110_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='sort_column',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
