# Generated by Django 3.2.11 on 2022-01-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0046_auto_20220114_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="compare_previous_period",
            field=models.BooleanField(
                default=False, verbose_name="Compare with previous period"
            ),
        ),
        migrations.AddField(
            model_name="widget",
            name="positive_decrease",
            field=models.BooleanField(default=False),
        ),
    ]
