# Generated by Django 3.2.11 on 2022-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0046_auto_20220114_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cypress/dashboard_images'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('metric', 'Metric'), ('table', 'Table'), ('mscolumn2d', 'Column'), ('stackedcolumn2d', 'Stacked Column'), ('msbar2d', 'Bar'), ('stackedbar2d', 'Stacked Bar'), ('msline', 'Line'), ('msline-stacked', 'Stacked Line'), ('pie2d', 'Pie'), ('msarea', 'Area'), ('doughnut2d', 'Donut'), ('scatter', 'Scatter'), ('funnel', 'Funnel'), ('pyramid', 'Pyramid'), ('radar', 'Radar'), ('bubble', 'Bubble'), ('heatmap', 'Heatmap'), ('timeseries-line', 'Line Timeseries'), ('timeseries-line_stacked', 'Stacked Line Timeseries'), ('timeseries-column', 'Column Timeseries'), ('timeseries-column-stacked', 'Stacked Column Timeseries'), ('timeseries-area', 'Area Timeseries'), ('mscombidy2d', 'Combination chart'), ('iframe', 'iframe')], default='mscolumn2d', max_length=32),
        ),
    ]
