# Generated by Django 3.2.11 on 2022-02-15 17:10

from django.db import migrations


def forward(apps, schema_editor):
    AggregationColumn = apps.get_model("columns", "AggregationColumn")
    columns = AggregationColumn.objects.filter(widget__kind="metric").all()
    for column in columns:
        column.rounding = column.widget.rounding_decimal

    AggregationColumn.objects.bulk_update(columns, ["rounding"])


def backward(apps, schema_editor):
    Widget = apps.get_model("widgets", "Widget")
    widgets = Widget.objects.filter(kind="metric").all()
    for widget in widgets:
        if column := widget.aggregations.first():
            widget.rounding_decimal = column.rounding

    Widget.objects.bulk_update(widgets, ["rounding_decimal"])


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0049_widget_part"),
        ("columns", "0017_auto_20220215_1443"),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=backward),
        migrations.RemoveField(
            model_name="widget",
            name="rounding_decimal",
        ),
    ]
