# Generated by Django 3.2.11 on 2022-02-15 17:10

from django.db import migrations


def forward(apps, schema_editor):
    AggregationColumn = apps.get_model("columns", "AggregationColumn")
    Widget = apps.get_model("widgets", "Widget")
    columns = []
    for widget in Widget.objects.filter(kind="metric").all():
        if column := widget.aggregations.first():
            column.rounding = widget.rounding_decimal
            columns.append(columns)

    AggregationColumn.objects.bulk_update(columns, ["rounding"])


def forward(apps, schema_editor):
    Widget = apps.get_model("widgets", "Widget")
    widgets = []
    for widget in Widget.objects.filter(kind="metric").all():
        if column := widget.aggregations.first():
            widget.rounding_decimal = column.rounding
            widgets.append(widget)

    Widget.objects.bulk_update(widgets, ["rounding_decimal"])


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0049_widget_part"),
        ("columns", "0017_auto_20220215_1443"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widget",
            name="rounding_decimal",
        ),
    ]
