# Generated by Django 3.2.11 on 2022-03-09 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('widgets', '0053_historicalwidget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalwidget',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical widget', 'verbose_name_plural': 'historical widgets'},
        ),
        migrations.AlterField(
            model_name='historicalwidget',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='HistoricalCombinationChart',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('kind', models.CharField(choices=[('line', 'Line'), ('area', 'Area'), ('column', 'Column')], default='column', max_length=32)),
                ('column', models.CharField(max_length=300)),
                ('function', models.CharField(choices=[('sum', 'Sum'), ('count', 'Count'), ('nunique', 'Count distinct'), ('mean', 'Average'), ('max', 'Maximum'), ('min', 'Minimum'), ('std', 'Standard deviation')], max_length=20)),
                ('on_secondary', models.BooleanField(default=False, help_text='Plot on a secondary Y-axis')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='widgets.widget')),
            ],
            options={
                'verbose_name': 'historical combination chart',
                'verbose_name_plural': 'historical combination charts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
