# Generated by Django 3.2.12 on 2022-03-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0055_auto_20220315_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwidget',
            name='first_segment_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='historicalwidget',
            name='fourth_segment_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='historicalwidget',
            name='lower_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalwidget',
            name='second_segment_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='historicalwidget',
            name='third_segment_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='historicalwidget',
            name='upper_limit',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='widget',
            name='first_segment_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='fourth_segment_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='lower_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='widget',
            name='second_segment_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='third_segment_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='upper_limit',
            field=models.IntegerField(default=100),
        ),
    ]
