# Generated by Django 3.2.12 on 2022-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0056_auto_20220315_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwidget',
            name='table_show_header',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='table_show_header',
            field=models.BooleanField(null=True),
        ),
    ]
