# Generated by Django 3.2.12 on 2022-05-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0057_auto_20220505_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwidget',
            name='show_tooltips',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='historicalwidget',
            name='table_show_header',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='show_tooltips',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='table_show_header',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
