# Generated by Django 3.2.13 on 2022-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0057_auto_20220506_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwidget',
            name='table_hide_data_type',
            field=models.BooleanField(blank=True, default=False, verbose_name='Hide data type icon'),
        ),
        migrations.AddField(
            model_name='widget',
            name='table_hide_data_type',
            field=models.BooleanField(blank=True, default=False, verbose_name='Hide data type icon'),
        ),
    ]
