# Generated by Django 4.0.4 on 2022-06-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0059_auto_20220516_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwidget',
            name='table_show_header',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show table header'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='table_show_header',
            field=models.BooleanField(blank=True, default=True, verbose_name='Show table header'),
        ),
    ]
