# Generated by Django 4.0.4 on 2022-10-29 07:49

from django.db import migrations

MAP = {
    "timeseries-line": "msline",
    "timeseries-line_stacked": "msline-stacked",
    "timeseries-column": "mscolumn2d",
    "timeseries-column-stacked": "stackedcolumn2d",
    "timeseries-area": "msarea",
    "pyramid": "funnel",
}


def forward(apps, schema_editor):
    Widget = apps.get_model("widgets", "Widget")
    timeseries_widgets = Widget.objects.filter(kind__in=list(MAP.keys())).all()
    for widget in timeseries_widgets:
        widget.kind = MAP[widget.kind]
    Widget.objects.bulk_update(timeseries_widgets, ["kind"])


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0061_remove_historicalwidget_sort_by_and_more"),
    ]

    operations = [migrations.RunPython(forward, reverse_code=migrations.RunPython.noop)]
