# Generated by Django 3.2.11 on 2022-02-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0017_alter_connector_basic_reports'),
        ('customreports', '0002_auto_20220128_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookadscustomreport',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='facebookadscustomreport',
            unique_together={('table_name', 'connector')},
        ),
    ]
