# Generated by Django 4.0.8 on 2023-01-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customreports', '0003_auto_20220203_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookAdsCustomReport',
        ),
    ]
