# Generated by Django 3.2 on 2021-05-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column", models.CharField(max_length=300)),
                (
                    "type",
                    models.CharField(
                        choices=[("INTEGER", "Integer"), ("STRING", "String")],
                        max_length=8,
                    ),
                ),
                (
                    "integer_predicate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("equal", "is equal to"),
                            ("nequal", "is not equal to"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("integer_value", models.BigIntegerField(blank=True, null=True)),
                (
                    "string_predicate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("starts_with", "starts with"),
                            ("ends_with", "ends with"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("string_value", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
