# Generated by Django 3.2 on 2021-05-03 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("widgets", "0005_auto_20210502_0405"),
        ("filters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filter",
            name="name",
        ),
        migrations.AddField(
            model_name="filter",
            name="column",
            field=models.CharField(default="Age", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filter",
            name="integer_predicate",
            field=models.CharField(
                choices=[("equal", "is equal to"), ("nequal", "is not equal to")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="filter",
            name="integer_value",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="filter",
            name="string_predicate",
            field=models.CharField(
                choices=[("starts_with", "starts with"), ("ends_with", "ends with")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="filter",
            name="string_value",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="filter",
            name="type",
            field=models.CharField(
                choices=[("integer", "Integer"), ("string", "String")],
                default="integer",
                max_length=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filter",
            name="widget",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="widgets.widget",
            ),
            preserve_default=False,
        ),
    ]
