# Generated by Django 4.0.8 on 2023-02-02 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        ('filters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfilter',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfilter',
            name='node',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='historicalfilter',
            name='widget',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='widgets.widget'),
        ),
        migrations.AddField(
            model_name='filter',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='filter',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='widgets.widget'),
        ),
    ]
