# Generated by Django 3.2 on 2021-05-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filters", "0002_auto_20210503_0224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="integer_predicate",
            field=models.CharField(
                blank=True,
                choices=[("equal", "is equal to"), ("nequal", "is not equal to")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="filter",
            name="integer_value",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filter",
            name="string_predicate",
            field=models.CharField(
                blank=True,
                choices=[("starts_with", "starts with"), ("ends_with", "ends with")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="filter",
            name="string_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filter",
            name="type",
            field=models.CharField(
                choices=[("INTEGER", "Integer"), ("STRING", "String")], max_length=8
            ),
        ),
    ]
