# Generated by Django 3.2 on 2021-05-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_widget_aggregator'),
        ('workflows', '0008_alter_node_kind'),
        ('filters', '0002_filter_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='workflows.node'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.widget'),
        ),
    ]
