# Generated by Django 3.2 on 2021-05-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_widget_aggregator'),
        ('filters', '0003_auto_20210514_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='widgets.widget'),
        ),
    ]
