# Generated by Django 3.2 on 2021-05-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0004_alter_filter_widget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='integer_predicate',
            new_name='numeric_predicate',
        ),
        migrations.AddField(
            model_name='filter',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='float_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='string_predicate',
            field=models.CharField(blank=True, choices=[('equal', 'is equal to'), ('nequal', 'is not equal to')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(choices=[('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('STRING', 'String'), ('BOOL', 'Bool')], max_length=8),
        ),
    ]
