# Generated by Django 3.2 on 2021-05-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0005_auto_20210517_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='boolean_value',
            new_name='bool_value',
        ),
    ]
