# Generated by Django 3.2 on 2021-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0006_rename_boolean_value_filter_bool_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='numeric_predicate',
            field=models.CharField(blank=True, choices=[('equal', 'is equal to'), ('nequal', 'is not equal to'), ('greaterthan', 'greater than'), ('greaterthanequal', 'greater than or equal to'), ('lessthan', 'less than'), ('lessthanequal', 'less than or equal')], max_length=16, null=True),
        ),
    ]
