# Generated by Django 3.2 on 2021-05-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0007_alter_filter_numeric_predicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='string_predicate',
            field=models.CharField(blank=True, choices=[('equal', 'is equal to'), ('nequal', 'is not equal to'), ('contains', 'contains'), ('notcontains', 'does not contain')], max_length=16, null=True),
        ),
    ]
