# Generated by Django 3.2 on 2021-05-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0008_alter_filter_string_predicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='string_predicate',
            field=models.CharField(blank=True, choices=[('equal', 'is equal to'), ('nequal', 'is not equal to'), ('contains', 'contains'), ('notcontains', 'does not contain'), ('startswith', 'starts with'), ('endswith', 'ends with')], max_length=16, null=True),
        ),
    ]
