# Generated by Django 3.2 on 2021-06-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0009_alter_filter_string_predicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='numeric_predicate',
            field=models.CharField(blank=True, choices=[('equal', 'is equal to'), ('nequal', 'is not equal to'), ('greaterthan', 'greater than'), ('greaterthanequal', 'greater than or equal to'), ('lessthan', 'less than'), ('lessthanequal', 'less than or equal'), ('isnull', 'is empty'), ('notnull', 'is not empty')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='string_predicate',
            field=models.CharField(blank=True, choices=[('equal', 'is equal to'), ('nequal', 'is not equal to'), ('contains', 'contains'), ('notcontains', 'does not contain'), ('startswith', 'starts with'), ('endswith', 'ends with'), ('isnull', 'is empty'), ('notnull', 'is not empty')], max_length=16, null=True),
        ),
    ]
