# Generated by Django 3.2 on 2021-06-04 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filters", "0011_alter_filter_string_predicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="filter",
            name="float_values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="filter",
            name="integer_values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="filter",
            name="string_values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="filter",
            name="numeric_predicate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equal", "is equal to"),
                    ("nequal", "is not equal to"),
                    ("greaterthan", "greater than"),
                    ("greaterthanequal", "greater than or equal to"),
                    ("lessthan", "less than"),
                    ("lessthanequal", "less than or equal"),
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("isin", "is any of"),
                    ("notin", "is none of"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="filter",
            name="string_predicate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equal", "is equal to"),
                    ("nequal", "is not equal to"),
                    ("contains", "contains"),
                    ("notcontains", "does not contain"),
                    ("startswith", "starts with"),
                    ("endswith", "ends with"),
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("isupper", "is uppercase"),
                    ("islower", "is lowercase"),
                    ("isin", "is any of"),
                    ("notin", "is none of"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
