# Generated by Django 3.2 on 2021-06-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0012_auto_20210604_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='string_predicate',
            field=models.CharField(blank=True, choices=[('equal', 'is equal to'), ('nequal', 'is not equal to'), ('contains', 'contains'), ('notcontains', 'does not contain'), ('startswith', 'starts with'), ('endswith', 'ends with'), ('isnull', 'is empty'), ('notnull', 'is not empty'), ('isin', 'is any of'), ('notin', 'is none of'), ('isupper', 'is uppercase'), ('islower', 'is lowercase')], max_length=16, null=True),
        ),
    ]
