# Generated by Django 3.2 on 2021-06-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0013_alter_filter_string_predicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='datetime_predicate',
            field=models.CharField(blank=True, choices=[('equal', 'is'), ('nequal', 'is not'), ('greaterthan', 'is before'), ('greaterthanequal', 'is on or before'), ('lessthan', 'is after'), ('lessthanequal', 'is on or after'), ('isnull', 'is empty'), ('notnull', 'is not empty')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='time_value',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
