# Generated by Django 3.2 on 2021-06-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filters", "0015_auto_20210610_1455"),
    ]

    operations = [
        migrations.AddField(
            model_name="filter",
            name="time_predicate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equal", "is"),
                    ("nequal", "is not"),
                    ("greaterthan", "is before"),
                    ("greaterthanequal", "is on or before"),
                    ("lessthan", "is after"),
                    ("lessthanequal", "is on or after"),
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="filter",
            name="datetime_predicate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equal", "is"),
                    ("nequal", "is not"),
                    ("greaterthan", "is before"),
                    ("greaterthanequal", "is on or before"),
                    ("lessthan", "is after"),
                    ("lessthanequal", "is on or after"),
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("today", "today"),
                    ("tomorrow", "tomorrow"),
                    ("yesterday", "yesterday"),
                    ("oneweekago", "one week ago"),
                    ("onemonthago", "one month ago"),
                    ("oneyearago", "one year ago"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
