# Generated by Django 3.2 on 2021-07-13 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
        ("filters", "0016_auto_20210614_0827"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="filter",
                    name="node",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to="nodes.node",
                    ),
                )
            ],  # You're reusing an existing table, so do nothing
            database_operations=[],
        )
    ]
