# Generated by Django 3.2.5 on 2021-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0017_alter_filter_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='bool_value',
            field=models.BooleanField(default=True),
        ),
    ]
