# Generated by Django 3.2.5 on 2021-08-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0018_alter_filter_bool_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='column',
            field=models.CharField(help_text='Column', max_length=300),
        ),
    ]
