# Generated by Django 3.2.6 on 2021-09-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0019_alter_filter_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={},
        ),
        migrations.AlterField(
            model_name='filter',
            name='datetime_predicate',
            field=models.CharField(blank=True, choices=[('equal', 'is'), ('nequal', 'is not'), ('lessthan', 'is before'), ('lessthanequal', 'is on or before'), ('greaterthan', 'is after'), ('greaterthanequal', 'is on or after'), ('isnull', 'is empty'), ('notnull', 'is not empty'), ('today', 'today'), ('tomorrow', 'tomorrow'), ('yesterday', 'yesterday'), ('oneweekago', 'one week ago'), ('onemonthago', 'one month ago'), ('oneyearago', 'one year ago')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='time_predicate',
            field=models.CharField(blank=True, choices=[('equal', 'is'), ('nequal', 'is not'), ('lessthan', 'is before'), ('lessthanequal', 'is on or before'), ('greaterthan', 'is after'), ('greaterthanequal', 'is on or after'), ('isnull', 'is empty'), ('notnull', 'is not empty')], max_length=16, null=True),
        ),
    ]
