# Generated by Django 3.2.7 on 2021-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0020_auto_20210907_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='date_value',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='datetime_predicate',
            field=models.CharField(choices=[('equal', 'is'), ('nequal', 'is not'), ('lessthan', 'is before'), ('lessthanequal', 'is on or before'), ('greaterthan', 'is after'), ('greaterthanequal', 'is on or after'), ('isnull', 'is empty'), ('notnull', 'is not empty'), ('today', 'today'), ('tomorrow', 'tomorrow'), ('yesterday', 'yesterday'), ('oneweekago', 'one week ago'), ('onemonthago', 'one month ago'), ('oneyearago', 'one year ago')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='datetime_value',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='float_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='integer_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='numeric_predicate',
            field=models.CharField(choices=[('equal', 'is equal to'), ('nequal', 'is not equal to'), ('greaterthan', 'greater than'), ('greaterthanequal', 'greater than or equal to'), ('lessthan', 'less than'), ('lessthanequal', 'less than or equal'), ('isnull', 'is empty'), ('notnull', 'is not empty'), ('isin', 'is any of'), ('notin', 'is none of')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='string_predicate',
            field=models.CharField(choices=[('equal', 'is equal to'), ('nequal', 'is not equal to'), ('contains', 'contains'), ('notcontains', 'does not contain'), ('startswith', 'starts with'), ('endswith', 'ends with'), ('isnull', 'is empty'), ('notnull', 'is not empty'), ('isin', 'is any of'), ('notin', 'is none of'), ('isupper', 'is uppercase'), ('islower', 'is lowercase')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='string_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='time_predicate',
            field=models.CharField(choices=[('equal', 'is'), ('nequal', 'is not'), ('lessthan', 'is before'), ('lessthanequal', 'is on or before'), ('greaterthan', 'is after'), ('greaterthanequal', 'is on or after'), ('isnull', 'is empty'), ('notnull', 'is not empty')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='time_value',
            field=models.TimeField(null=True),
        ),
    ]
