# Generated by Django 3.2.7 on 2021-12-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0021_auto_20210914_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='datetime_predicate',
            field=models.CharField(choices=[('equal', 'is'), ('nequal', 'is not'), ('lessthan', 'is before'), ('lessthanequal', 'is on or before'), ('greaterthan', 'is after'), ('greaterthanequal', 'is on or after'), ('isnull', 'is empty'), ('notnull', 'is not empty'), ('today', 'today'), ('tomorrow', 'tomorrow'), ('yesterday', 'yesterday'), ('oneweekago', 'one week ago'), ('onemonthago', 'one month ago'), ('oneyearago', 'one year ago'), ('thisweek', 'This week (starts Monday)'), ('thisweekuptodate', 'This week (starts Monday) up to date'), ('lastweek', 'Last week (starts Monday)'), ('last7', 'Last 7 days'), ('last14', 'Last 14 days'), ('last28', 'Last 28 days'), ('thismonth', 'This month'), ('thismonthuptodate', 'This month to date'), ('lastmonth', 'Last month'), ('last30', 'Last 30 days'), ('last90', 'Last 90 days'), ('thisquarter', 'This quarter'), ('thisquarteruptodate', 'This quarter up to date'), ('lastquarter', 'Last quarter'), ('last180', 'Last 180 days'), ('last12month', 'Last 12 months'), ('lastyear', 'Last calendar year'), ('thisyear', 'This year'), ('thisyearuptodate', 'This year (January - up to date)')], max_length=20, null=True),
        ),
    ]
