# Generated by Django 3.2.12 on 2022-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0026_alter_filter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='struct_predicate',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty')], max_length=16, null=True, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='historicalfilter',
            name='struct_predicate',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty')], max_length=16, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(choices=[('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('STRING', 'String'), ('BOOL', 'Bool'), ('TIME', 'Time'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('STRUCT', 'Dictionary')], max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalfilter',
            name='type',
            field=models.CharField(choices=[('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('STRING', 'String'), ('BOOL', 'Bool'), ('TIME', 'Time'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('STRUCT', 'Dictionary')], max_length=8),
        ),
    ]
