# Generated by Django 3.2.12 on 2022-04-25 15:04

from django.db import migrations, models


def forward(apps, schema_editor):
    Filter = apps.get_model("filters", "Filter")
    filters = Filter.objects.all()

    for f in filters:
        f.bool_predicate = "istrue" if f.bool_value else "isfalse"

    Filter.objects.bulk_update(filters, ["bool_predicate"])

    FilterHistory = apps.get_model("filters", "HistoricalFilter")

    historic_filters = FilterHistory.objects.all()

    for f in historic_filters:
        f.bool_predicate = "istrue" if f.bool_value else "isfalse"

    FilterHistory.objects.bulk_update(historic_filters, ["bool_predicate"])


def backward(apps, schema_editor):
    Filter = apps.get_model("filters", "Filter")
    filters = Filter.objects.all()

    for f in filters:
        f.bool_value = f.bool_predicate == "istrue"

    Filter.objects.bulk_update(filters, ["bool_value"])

    FilterHistory = apps.get_model("filters", "HistoricalFilter")

    historic_filters = FilterHistory.objects.all()

    for f in historic_filters:
        f.bool_value = f.bool_predicate == "istrue"

    FilterHistory.objects.bulk_update(historic_filters, ["bool_value"])


class Migration(migrations.Migration):

    dependencies = [
        ("filters", "0027_auto_20220330_1249"),
    ]

    operations = [
        migrations.AddField(
            model_name="filter",
            name="bool_predicate",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("istrue", "is true"),
                    ("isfalse", "is false"),
                ],
                default="istrue",
                max_length=16,
                verbose_name="Condition",
            ),
        ),
        migrations.AddField(
            model_name="historicalfilter",
            name="bool_predicate",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("istrue", "is true"),
                    ("isfalse", "is false"),
                ],
                default="istrue",
                max_length=16,
                verbose_name="Condition",
            ),
        ),
        migrations.RunPython(forward, reverse_code=backward),
        migrations.RemoveField(
            model_name="filter",
            name="bool_value",
        ),
        migrations.RemoveField(
            model_name="historicalfilter",
            name="bool_value",
        ),
    ]
