# Generated by Django 3.2.6 on 2021-09-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_templateintegration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='templateinstance',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='templateintegration',
            options={'ordering': ('-updated',)},
        ),
    ]
