# Generated by Django 4.0.8 on 2023-02-02 22:41

import apps.base.clone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('sheet', 'Sheet'), ('upload', 'Upload'), ('connector', 'Connector'), ('customapi', 'Custom API')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('update', 'Update'), ('pending', 'Pending'), ('load', 'Load'), ('error', 'Error'), ('done', 'Done')], default='update', max_length=16)),
                ('ready', models.BooleanField(default=False)),
                ('created_ready', models.DateTimeField(null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
    ]
