# Generated by Django 3.2 on 2021-05-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='file',
            field=models.FileField(null=True, upload_to='floris.list@gyana.co.uk/integrations'),
        ),
    ]
