# Generated by Django 3.2 on 2021-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integration_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='file',
            field=models.FileField(null=True, upload_to='sascha.hofmann@gyana.co.uk/integrations'),
        ),
    ]
