# Generated by Django 3.2 on 2021-05-14 11:23

import apps.integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20210514_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='file',
            field=models.FileField(null=True, upload_to=apps.integrations.models.DynamicUploadPath()),
        ),
    ]
