# Generated by Django 3.2 on 2021-05-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_integration_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='cell_range',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
