# Generated by Django 3.2 on 2021-05-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_integration_cell_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='cell_range',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
