# Generated by Django 3.2 on 2021-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_alter_integration_cell_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='enable_sync_emails',
            field=models.BooleanField(default=True),
        ),
    ]
