# Generated by Django 3.2 on 2021-06-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_integration_enable_sync_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='file',
            field=models.TextField(null=True),
        ),
    ]
