# Generated by Django 3.2.5 on 2021-08-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0011_auto_20210721_1256"),
        # migration happens after these are created to enable copy of data
        ("connectors", "0001_initial"),
        ("sheets", "0001_initial"),
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="cell_range",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="external_table_sync_task_id",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="file",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="fivetran_authorized",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="fivetran_id",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="fivetran_poll_historical_sync_task_id",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="has_initial_sync",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="historical_sync_complete",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="last_synced",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="schema",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="service",
        ),
        migrations.RemoveField(
            model_name="integration",
            name="url",
        ),
        migrations.AlterField(
            model_name="integration",
            name="kind",
            field=models.CharField(
                choices=[
                    ("sheets", "Google Sheets"),
                    ("upload", "Upload"),
                    ("connector", "Connector"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunSQL(
            """UPDATE integrations_integration
                SET kind = CASE
                        WHEN kind = 'csv' THEN 'upload'
                        WHEN kind = 'google_sheets' THEN 'sheet'
                        WHEN kind = 'fivetran' THEN 'connetor'
                    END
                """
        ),
    ]
