# Generated by Django 3.2.5 on 2021-08-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_auto_20210806_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='enable_sync_emails',
        ),
        migrations.AlterField(
            model_name='integration',
            name='kind',
            field=models.CharField(choices=[('sheet', 'Google Sheets'), ('upload', 'Upload'), ('connector', 'Connector')], max_length=32),
        ),
    ]
