# Generated by Django 3.2.5 on 2021-08-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0013_auto_20210808_1020"),
    ]

    operations = [
        migrations.RunSQL(
            """UPDATE integrations_integration
                SET kind = 'connector'
                WHERE kind = 'connetor'
                """,
            reverse_sql="""UPDATE integrations_integration
                SET kind = 'connetor'
                WHERE kind = 'connector'
                """,
        ),
    ]
