# Generated by Django 3.2.5 on 2021-08-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_auto_20210809_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='created_ready',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='integration',
            name='state',
            field=models.CharField(choices=[('load', 'Load'), ('error', 'Error'), ('done', 'Done')], default='load', max_length=16),
        ),
    ]
