# Generated by Django 3.2.5 on 2021-08-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0015_auto_20210810_1619"),
    ]

    operations = [
        migrations.RunSQL(
            """DELETE FROM sheets_sheet WHERE integration_id is NULL""",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """DELETE FROM uploads_upload WHERE integration_id is NULL""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
