# Generated by Django 3.2.5 on 2021-08-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0016_auto_20210810_1620"),
    ]

    operations = [
        migrations.RunSQL(
            """
        UPDATE integrations_integration
        SET state = 'done',
            ready = True,
            created_ready = created
        ;
        """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
