# Generated by Django 3.2.5 on 2021-08-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_auto_20210811_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='kind',
            field=models.CharField(choices=[('sheet', 'Sheet'), ('upload', 'Upload'), ('connector', 'Connector')], max_length=32),
        ),
    ]
