# Generated by Django 3.2.5 on 2021-08-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_alter_integration_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='state',
            field=models.CharField(choices=[('update', 'Update'), ('load', 'Load'), ('error', 'Error'), ('done', 'Done')], default='update', max_length=16),
        ),
    ]
