# Generated by Django 3.2.7 on 2021-12-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0022_alter_integration_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="kind",
            field=models.CharField(
                choices=[
                    ("sheet", "Sheet"),
                    ("upload", "Upload"),
                    ("connector", "Connector"),
                    ("custom_api", "Custom API"),
                ],
                max_length=32,
            ),
        ),
    ]
