# Generated by Django 3.2.7 on 2021-12-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0023_alter_integration_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='kind',
            field=models.CharField(choices=[('sheet', 'Sheet'), ('upload', 'Upload'), ('connector', 'Connector'), ('customapi', 'Custom API')], max_length=32),
        ),
    ]
