# Generated by Django 3.2.7 on 2021-12-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0024_alter_integration_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
