# Generated by Django 3.2.7 on 2021-12-21 01:06

from django.db import migrations, models


class Kind(models.TextChoices):
    SHEET = "sheet", "Sheet"
    UPLOAD = "upload", "Upload"
    CONNECTOR = "connector", "Connector"
    CUSTOMAPI = "customapi", "Custom API"


def forwards(apps, schema_editor):
    Integration = apps.get_model("integrations", "Integration")

    for integration in Integration.objects.iterator():
        if integration.kind == Kind.CONNECTOR:
            integration.is_scheduled = True
        elif integration.kind == Kind.SHEET:
            integration.is_scheduled = integration.sheet.is_scheduled
        else:
            integration.is_scheduled = False

        integration.save()


def backwards(apps, schema_editor):
    Integration = apps.get_model("integrations", "Integration")

    for integration in Integration.objects.iterator():
        if integration.kind == Kind.SHEET:
            integration.sheet.is_scheduled = integration.is_scheduled
            integration.sheet.save()


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0025_integration_is_scheduled"),
    ]

    operations = [migrations.RunPython(forwards, reverse_code=backwards)]
