# Generated by Django 4.0.8 on 2023-01-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0026_auto_20211221_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='kind',
            field=models.CharField(choices=[('sheet', 'Sheet'), ('upload', 'Upload'), ('customapi', 'Custom API')], max_length=32),
        ),
    ]
