# Generated by Django 4.0.8 on 2023-02-02 22:41

import apps.base.clone
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('failed', 'Failed'), ('success', 'Success')], max_length=8)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('task_id', models.UUIDField(null=True)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, apps.base.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=8)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('task_id', models.UUIDField(null=True)),
                ('source', models.CharField(choices=[('integration', 'Integration'), ('workflow', 'Workflow')], max_length=16)),
                ('graph_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='runs.graphrun')),
                ('integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='integrations.integration')),
                ('result', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.taskresult')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, apps.base.clone.CloneMixin, models.Model),
        ),
    ]
