# Generated by Django 4.0.8 on 2023-02-02 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('runs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='graphrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='graphrun',
            name='result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.taskresult'),
        ),
        migrations.AddField(
            model_name='graphrun',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
