# Generated by Django 3.2.7 on 2021-12-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_graphrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='graph_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='runs.graphrun'),
        ),
    ]
