# Generated by Django 3.2.7 on 2021-12-14 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_jobrun_graph_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='graph_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='runs.graphrun'),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('failed', 'Failed'), ('success', 'Success')], default='pending', max_length=8),
        ),
    ]
