# Generated by Django 4.0.8 on 2023-02-02 22:41

import apps.base.clone
import apps.customapis.models
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=2048, null=True)),
                ('json_path', models.TextField(default='$', validators=[apps.customapis.models.validate_json_path])),
                ('ndjson_file', models.FileField(null=True, upload_to='cypress/customapi_ndjson')),
                ('http_request_method', models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('CONNECT', 'CONNECT'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE'), ('PATCH', 'PATCH')], default='GET', max_length=8)),
                ('authorization', models.CharField(choices=[('no_auth', 'No Auth'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth'), ('digest_auth', 'Digest Auth'), ('oauth2', 'OAuth2')], default='no_auth', max_length=16)),
                ('api_key_key', models.CharField(max_length=8192, null=True)),
                ('api_key_value', django_cryptography.fields.encrypt(models.CharField(max_length=8192, null=True))),
                ('api_key_add_to', models.CharField(choices=[('http_header', 'HTTP Header'), ('query_params', 'Query Params')], default='http_header', max_length=8192)),
                ('bearer_token', django_cryptography.fields.encrypt(models.CharField(max_length=1024, null=True))),
                ('username', models.CharField(max_length=1024, null=True)),
                ('password', django_cryptography.fields.encrypt(models.CharField(max_length=1024, null=True))),
                ('body', models.CharField(choices=[('none', 'none'), ('form-data', 'form-data'), ('x-www-form-urlencoded', 'x-www-form-urlencoded'), ('raw', 'raw'), ('binary', 'binary')], default='none', max_length=32)),
                ('body_raw', models.TextField(null=True)),
                ('body_binary', models.FileField(null=True, upload_to='cypress/customapi_body_binary', validators=[apps.customapis.models.validate_body_binary])),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QueryParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=1024)),
                ('value', models.CharField(max_length=1024)),
                ('customapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queryparams', to='customapis.customapi')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HttpHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=8192)),
                ('value', models.CharField(max_length=8192)),
                ('customapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='httpheaders', to='customapis.customapi')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FormURLEncodedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=8192)),
                ('value', models.CharField(max_length=8192)),
                ('customapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formurlencodedentries', to='customapis.customapi')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FormDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=4)),
                ('key', models.CharField(max_length=8192)),
                ('text', models.CharField(max_length=8192)),
                ('file', models.FileField(null=True, upload_to='cypress/formdataentry_file', validators=[apps.customapis.models.validate_body_binary])),
                ('customapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formdataentries', to='customapis.customapi')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
    ]
