# Generated by Django 3.2.7 on 2021-12-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customapi',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
