# Generated by Django 4.0.8 on 2023-02-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customapis', '0002_initial'),
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customapi',
            name='oauth2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth2.oauth2'),
        ),
    ]
