# Generated by Django 3.2.7 on 2021-12-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapis', '0002_alter_customapi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customapi',
            name='http_request_method',
            field=models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('CONNECT', 'CONNECT'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE'), ('PATCH', 'PATCH')], default='GET', max_length=8),
        ),
    ]
