# Generated by Django 3.2.7 on 2021-12-17 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customapis', '0003_customapi_http_request_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=1024)),
                ('value', models.CharField(max_length=1024)),
                ('customapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customapis.customapi')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
    ]
