# Generated by Django 3.2.7 on 2021-12-17 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customapis', '0004_queryparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryparam',
            name='customapi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queryparams', to='customapis.customapi'),
        ),
        migrations.CreateModel(
            name='HttpHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=8192)),
                ('value', models.CharField(max_length=8192)),
                ('customapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='customapis.customapi')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
    ]
