# Generated by Django 3.2.7 on 2021-12-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customapis', '0005_auto_20211217_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='customapi',
            name='api_key_add_to',
            field=models.CharField(choices=[('http_header', 'HTTP Header'), ('query_params', 'Query Params')], default='http_header', max_length=8192),
        ),
        migrations.AddField(
            model_name='customapi',
            name='api_key_key',
            field=models.CharField(max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='customapi',
            name='api_key_value',
            field=models.CharField(max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='customapi',
            name='authorization',
            field=models.CharField(choices=[('no_auth', 'No Auth'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth'), ('digest_auth', 'Digest Auth')], default='no_auth', max_length=16),
        ),
        migrations.AddField(
            model_name='customapi',
            name='bearer_token',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='customapi',
            name='password',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='customapi',
            name='username',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='httpheader',
            name='customapi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='httpheaders', to='customapis.customapi'),
        ),
    ]
