# Generated by Django 3.2.7 on 2021-12-19 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
        ('customapis', '0006_auto_20211217_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='customapi',
            name='oauth2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth2.oauth2'),
        ),
        migrations.AlterField(
            model_name='customapi',
            name='authorization',
            field=models.CharField(choices=[('no_auth', 'No Auth'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Auth'), ('digest_auth', 'Digest Auth'), ('oauth2', 'OAuth2')], default='no_auth', max_length=16),
        ),
    ]
