# Generated by Django 3.2.7 on 2021-12-19 22:06

import apps.customapis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapis', '0007_auto_20211219_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customapi',
            name='json_path',
            field=models.TextField(default='$', validators=[apps.customapis.models.validate_json_path]),
        ),
    ]
