# Generated by Django 3.2.7 on 2021-12-20 00:40

import apps.customapis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customapis', '0008_alter_customapi_json_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='customapi',
            name='body',
            field=models.CharField(choices=[('none', 'none'), ('form-data', 'form-data'), ('x-www-form-urlencoded', 'x-www-form-urlencoded'), ('raw', 'raw'), ('binary', 'binary')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='customapi',
            name='body_binary',
            field=models.FileField(null=True, upload_to='cypress/customapi_body_binary', validators=[apps.customapis.models.validate_body_binary]),
        ),
        migrations.AddField(
            model_name='customapi',
            name='body_raw',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customapi',
            name='ndjson_file',
            field=models.FileField(null=True, upload_to='cypress/customapi_ndjson'),
        ),
        migrations.CreateModel(
            name='FormURLEncodedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=8192)),
                ('value', models.CharField(max_length=8192)),
                ('customapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formurlencodedentries', to='customapis.customapi')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=4)),
                ('key', models.CharField(max_length=8192)),
                ('text', models.CharField(max_length=8192)),
                ('file', models.FileField(null=True, upload_to='cypress/formdataentry_file', validators=[apps.customapis.models.validate_body_binary])),
                ('customapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formdataentries', to='customapis.customapi')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
    ]
