# Generated by Django 3.2.7 on 2021-12-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapis', '0009_auto_20211220_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customapi',
            name='url',
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
