# Generated by Django 3.2 on 2021-05-20 01:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_dashboard_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='sort_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
