# Generated by Django 3.2 on 2021-06-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_dashboard_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='sort_order',
        ),
    ]
