# Generated by Django 3.2 on 2021-06-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_remove_dashboard_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
