# Generated by Django 3.2.5 on 2021-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_dashboard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='shared_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='shared_status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=16),
        ),
    ]
