# Generated by Django 3.2.5 on 2021-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_auto_20210723_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='height',
            field=models.IntegerField(default=840),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='width',
            field=models.IntegerField(default=1200),
        ),
    ]
