# Generated by Django 3.2.7 on 2021-09-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_alter_dashboard_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='shared_status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('password_protected', 'Password-protected')], default='private', max_length=20),
        ),
    ]
