# Generated by Django 3.2.7 on 2021-10-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_auto_20210929_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='password_set',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
