# Generated by Django 3.2.7 on 2021-11-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0011_auto_20211105_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="grid_size",
            field=models.IntegerField(default=15),
        ),
    ]
