# Generated by Django 3.2.7 on 2021-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_dashboard_grid_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
