# Generated by Django 3.2.7 on 2021-11-12 13:43

import django.contrib.postgres.fields
from django.db import migrations, models


def getFusionThemePalette():
    return [
        "#5D62B5",
        "#29C3BE",
        "#F2726F",
        "#FFC533",
        "#62B58F",
        "#BC95DF",
        "#67CDF2",
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0013_alter_dashboard_background_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="palette_colors",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="palette_colors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(default="#5D62B5", max_length=7),
                default=getFusionThemePalette,
                size=10,
            ),
        ),
    ]
