# Generated by Django 3.2.7 on 2021-11-12 11:11

import apps.dashboards.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_alter_dashboard_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='palette_colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='#5D62B5', max_length=7), default=apps.dashboards.models.getFusionThemePalette, size=10),
        ),
    ]
