# Generated by Django 3.2.7 on 2021-11-15 21:54

import django.contrib.postgres.fields
from django.db import migrations, models

import apps.dashboards.models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0014_alter_dashboard_palette_colors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="palette_colors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(default="#5D62B5", max_length=7),
                default=apps.dashboards.models.getDefaultThemePalette,
                size=10,
            ),
        ),
    ]
