# Generated by Django 3.2.7 on 2021-12-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_alter_dashboard_palette_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='shared_status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('password_protected', 'Password Protected')], default='private', max_length=20),
        ),
    ]
