# Generated by Django 3.2.7 on 2021-12-10 07:40

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, schema_editor):
    """Create the first page for every dashboard"""
    Dashboard = apps.get_model("dashboards", "Dashboard")
    db_alias = schema_editor.connection.alias

    for dashboard in Dashboard.objects.using(db_alias).iterator():
        dashboard.pages.create()


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0016_alter_dashboard_shared_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("position", models.IntegerField(default=1)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="dashboards.dashboard",
                    ),
                ),
            ],
            options={
                "unique_together": {("dashboard", "position")},
            },
        ),
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop),
    ]
