# Generated by Django 3.2.7 on 2021-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='font_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='font_family',
            field=models.CharField(choices=[('Boogaloo', 'Boogaloo'), ('Lato', 'Lato'), ('Merriweather', 'Merriweather'), ('Montserrat', 'Montserrat'), ('Open Sans', 'Open Sans'), ('Roboto', 'Roboto'), ('Ubuntu', 'Ubuntu')], default='Roboto', max_length=30),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='font_size',
            field=models.IntegerField(default='16'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='show_widget_border',
            field=models.BooleanField(default=True),
        ),
    ]
