# Generated by Django 3.2.7 on 2021-12-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0018_auto_20211216_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='font_color',
            field=models.CharField(default='#6a6b77', max_length=7),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='font_size',
            field=models.IntegerField(default='14'),
        ),
    ]
