# Generated by Django 3.2.7 on 2021-12-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0019_auto_20211217_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='snap_to_grid',
            field=models.BooleanField(default=True),
        ),
    ]
