# Generated by Django 3.2.7 on 2022-01-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0020_dashboard_snap_to_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='widget_background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='widget_border_color',
            field=models.CharField(default='#e6e6e6', max_length=7),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='widget_border_radius',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='widget_border_thickness',
            field=models.IntegerField(default=1),
        ),
    ]
