# Generated by Django 3.2.11 on 2022-01-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0021_auto_20220105_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='show_widget_headers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='widget_header_font_size',
            field=models.IntegerField(default='18'),
        ),
    ]
