# Generated by Django 3.2.11 on 2022-03-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0022_auto_20220105_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='shared_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
