# Generated by Django 3.2.11 on 2022-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0023_alter_dashboard_shared_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
