# Generated by Django 3.2.11 on 2022-03-08 11:55

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0024_page_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('dashboard', 'position'), name='dashboards_page_dashboard_id_position'),
        ),
    ]
