# Generated by Django 3.2.11 on 2022-03-09 13:48

from django.core.management import call_command
from django.db import connection, migrations


def forward(apps, schema_editor):
    cursor = connection.cursor()
    cursor.execute('TRUNCATE TABLE "widgets_historicalwidget"')
    call_command("populate_history", "--auto")


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0026_auto_20220309_1346"),
        ("filters", "0025_historicalfilter"),
        ("controls", "0007_auto_20220309_1346"),
        (
            "columns",
            "0020_historicaladdcolumn_historicalaggregationcolumn_historicalcolumn_historicalconvertcolumn_historicale",
        ),
        ("widgets", "0054_auto_20220309_1346"),
    ]

    operations = [migrations.RunPython(forward, reverse_code=migrations.RunPython.noop)]
