# Generated by Django 3.2.12 on 2022-03-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0026_auto_20220309_1346"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardversion",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
