# Generated by Django 3.2.12 on 2022-03-21 14:12

import django.db.models.deletion
from django.db import migrations, models

import apps.base.clone


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dashboards", "0027_dashboardversion_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="dashboards.dashboard",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated",),
                "abstract": False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
    ]
