# Generated by Django 3.2.12 on 2022-03-31 14:44
from django.db import migrations

from apps.dashboards.models import DashboardUpdate


def delete_historic(apps, schema, model_name):
    model_history_class = apps.get_model(schema, f"Historical{model_name}")
    model_history_class.objects.all().delete()


def forward(apps, schema_editor):
    DashboardUpdate = apps.get_model("dashboards", "DashboardUpdate")
    DashboardVersion = apps.get_model("dashboards", "DashboardVersion")
    DashboardUpdate.objects.all().delete()
    DashboardVersion.objects.all().delete()

    delete_historic(apps, "dashboards", "Dashboard")
    delete_historic(apps, "dashboards", "Page")

    delete_historic(apps, "widgets", "Widget")
    delete_historic(apps, "widgets", "CombinationChart")

    delete_historic(apps, "columns", "AddColumn")
    delete_historic(apps, "columns", "AggregationColumn")
    delete_historic(apps, "columns", "Column")
    delete_historic(apps, "columns", "ConvertColumn")
    delete_historic(apps, "columns", "EditColumn")
    delete_historic(apps, "columns", "FormulaColumn")
    delete_historic(apps, "columns", "JoinColumn")
    delete_historic(apps, "columns", "RenameColumn")
    delete_historic(apps, "columns", "SecondaryColumn")
    delete_historic(apps, "columns", "SortColumn")
    delete_historic(apps, "columns", "WindowColumn")

    delete_historic(apps, "controls", "Control")
    delete_historic(apps, "controls", "ControlWidget")

    delete_historic(apps, "filters", "Filter")


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0028_dashboardupdate"),
    ]

    operations = [migrations.RunPython(forward, reverse_code=migrations.RunPython.noop)]
