# Generated by Django 3.2.13 on 2022-05-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0029_auto_20220331_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='extra_css',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='extra_html_head',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldashboard',
            name='extra_css',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldashboard',
            name='extra_html_head',
            field=models.TextField(null=True),
        ),
    ]
