# Generated by Django 3.2.13 on 2022-05-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0030_auto_20220525_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='font_color',
            field=models.CharField(default='#242733', max_length=7),
        ),
        migrations.AlterField(
            model_name='historicaldashboard',
            name='font_color',
            field=models.CharField(default='#242733', max_length=7),
        ),
    ]
