# Generated by Django 4.0.4 on 2022-06-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0031_auto_20220525_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='preview_by_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldashboard',
            name='preview_by_default',
            field=models.BooleanField(default=False),
        ),
    ]
