# Generated by Django 3.2.7 on 2021-12-19 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0013_project_periodic_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuth2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("client_id", models.CharField(max_length=1024)),
                ("client_secret", models.CharField(max_length=1024)),
                ("authorization_base_url", models.URLField(max_length=2048)),
                ("token_url", models.URLField(max_length=2048)),
                ("scope", models.CharField(blank=True, max_length=1024)),
                ("state", models.CharField(max_length=1024, null=True)),
                ("token", models.JSONField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated",),
                "abstract": False,
            },
        ),
    ]
