# Generated by Django 4.0.8 on 2023-02-02 22:41

import apps.base.clone
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=1024)),
                ('client_secret', django_cryptography.fields.encrypt(models.CharField(max_length=1024))),
                ('authorization_base_url', models.URLField(max_length=2048)),
                ('token_url', models.URLField(max_length=2048)),
                ('scope', models.CharField(blank=True, max_length=1024)),
                ('state', models.CharField(max_length=1024, null=True)),
                ('token', models.JSONField(null=True)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
    ]
