# Generated by Django 3.2.7 on 2021-12-21 00:05

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2',
            name='client_secret',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=1024)),
        ),
    ]
