# Generated by Django 4.0.8 on 2023-02-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
