# Generated by Django 3.2.7 on 2021-09-24 16:40

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cnames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cname',
            name='domain',
            field=models.CharField(max_length=253, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-_]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z0-9][A-Za-z0-9-_]{0,61}[A-Za-z]$'), 'Must be a valid domain')]),
        ),
    ]
