# Generated by Django 3.2.7 on 2021-09-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_team_icon'),
        ('cnames', '0002_alter_cname_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cname',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
