# Generated by Django 3.2.7 on 2021-10-21 14:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cnames', '0003_alter_cname_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cname',
            name='domain',
            field=models.CharField(error_messages={'unique': "A CNAME with this domain already exists. If you think this is a mistake, reach out to support and we'll sort it out for you."}, max_length=253, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-_]{0,61}[A-Za-z0-9])?\\.)+[A-Za-z0-9][A-Za-z0-9-_]{0,61}[A-Za-z]$'), 'Must be a valid domain')]),
        ),
    ]
