# Generated by Django 4.0.8 on 2023-02-02 22:41

from django.db import migrations

# todo: delete file


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
