# Generated by Django 4.0.8 on 2023-02-02 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='export',
            name='integration_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='tables.table'),
        ),
        migrations.AddField(
            model_name='export',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='nodes.node'),
        ),
    ]
