# Generated by Django 4.0.8 on 2024-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="export",
            name="file",
            field=models.FileField(default="", upload_to="exports/"),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "UPDATE exports_export SET file = 'exports/export_' || id || '_' || gcs_id || '.csv';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name="export",
            name="gcs_id",
        ),
    ]
