# Generated by Django 3.2 on 2021-05-17 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='data_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 17, 23, 39, 20, 976112)),
            preserve_default=False,
        ),
    ]
