# Generated by Django 3.2 on 2021-05-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_table_data_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='num_rows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
