# Generated by Django 3.2 on 2021-06-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_table_num_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='source',
            field=models.CharField(choices=[('integration', 'Integration'), ('workflow_node', 'Workflow node'), ('pivot_node', 'Pivot Node')], max_length=16),
        ),
    ]
