# Generated by Django 3.2 on 2021-05-10 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0007_auto_20210510_0203"),
        ("tables", "0003_table_source"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='table',
        #     name='connector',
        # ),
        migrations.AlterField(
            model_name="table",
            name="dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="datasets.dataset",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="source",
            field=models.CharField(
                choices=[("dataset", "Dataset"), ("dataflow_node", "Dataflow node")],
                max_length=16,
            ),
        ),
    ]
