# Generated by Django 3.2 on 2021-06-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0027_auto_20210622_0918'),
        ('tables', '0004_alter_table_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pivot_node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pivot_node', to='workflows.node'),
        ),
        migrations.AlterField(
            model_name='table',
            name='source',
            field=models.CharField(choices=[('integration', 'Integration'), ('workflow_node', 'Workflow node'), ('pivot_node', 'Pivot node')], max_length=16),
        ),
    ]
