# Generated by Django 3.2 on 2021-06-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0031_rename_updated_node_data_updated'),
        ('tables', '0005_auto_20210622_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='pivot_node',
        ),
        migrations.AddField(
            model_name='table',
            name='intermediate_node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_node', to='workflows.node'),
        ),
        migrations.AlterField(
            model_name='table',
            name='source',
            field=models.CharField(choices=[('integration', 'Integration'), ('workflow_node', 'Workflow node'), ('intermediate_node', 'Intermediate node')], max_length=18),
        ),
    ]
