# Generated by Django 3.2 on 2021-07-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20210713_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='bq_table',
        ),
        migrations.AddField(
            model_name='table',
            name='_bq_table',
            field=models.CharField(db_column='bq_table', max_length=1024, null=True),
        ),
    ]
