# Generated by Django 3.2 on 2021-07-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_auto_20210713_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='bq_table',
        ),
    ]
