# Generated by Django 3.2.5 on 2021-08-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20210716_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('_bq_table', 'bq_dataset')},
        ),
    ]
