# Generated by Django 3.2.5 on 2021-08-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20210812_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='num_rows',
            field=models.IntegerField(default=0),
        ),
    ]
