# Generated by Django 3.2.5 on 2021-08-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0012_migrate_bigquery_datasets_and_tables"),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='_bq_table',
            new_name='bq_table',
        ),
        migrations.AlterField(
            model_name="table", name="bq_table", field=models.CharField(max_length=1024)
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("bq_table", "bq_dataset")},
        ),
    ]
