# Generated by Django 3.2.11 on 2022-01-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_auto_20210928_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='copied_from',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
