# Generated by Django 3.2.11 on 2022-02-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0023_auto_20220208_1139'),
        ('tables', '0015_table_copied_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='cache_node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_table', to='nodes.node'),
        ),
        migrations.AlterField(
            model_name='table',
            name='intermediate_node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_table', to='nodes.node'),
        ),
    ]
