# Generated by Django 4.0.8 on 2025-01-30 22:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_industry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='marketing_allowed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='source_channel',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='profile-pictures/'),
        ),
    ]
