# Generated by Django 3.2.6 on 2021-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
