# Generated by Django 3.2.6 on 2021-08-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_industry',
            field=models.CharField(choices=[('agency', 'Agency'), ('software', 'Software'), ('ecommerce', 'E-commerce'), ('consulting', 'Consulting'), ('education', 'Education'), ('fintech', 'Fintech'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_role',
            field=models.CharField(choices=[('leadership', 'Leadership'), ('marketing', 'Marketing'), ('business analyst', 'Business Analyst'), ('data scientist', 'Data Scientist'), ('product manager', 'Product Manager'), ('developer', 'Developer'), ('student', 'Student'), ('sales', 'Sales'), ('other', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_size',
            field=models.CharField(choices=[('1', 'Just me'), ('2-10', '2-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-1000', 'Two Hundred And One To One Thousand'), ('more than 1000', 'More than 1000')], max_length=16, null=True),
        ),
    ]
