# Generated by Django 3.2.6 on 2021-08-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210827_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_size',
            field=models.CharField(choices=[('1', 'Just me'), ('2-10', '2-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-1000', '201-1000'), ('more than 1000', 'More than 1000')], max_length=16, null=True),
        ),
    ]
