# Generated by Django 3.2.7 on 2021-09-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marketing_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
