# Generated by Django 3.2.7 on 2021-11-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedWaitlistEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovedWaitlistEmailBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.FileField(upload_to='cypress/approved_waitlist_batch')),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
    ]
