# Generated by Django 3.2.7 on 2021-11-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_approvedwaitlistemail_approvedwaitlistemailbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedwaitlistemail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
