# Generated by Django 3.2.11 on 2022-02-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_approvedwaitlistemail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='marketing_allowed',
            field=models.BooleanField(null=True),
        ),
    ]
