# Generated by Django 3.2.12 on 2022-05-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_marketing_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='source_channel',
            field=models.CharField(choices=[('searchengine', 'Search engine'), ('socialmedia', 'Social media'), ('wordofmouth', 'Recommended by someone'), ('other', 'Other')], max_length=32, null=True),
        ),
    ]
