# Generated by Django 3.2.12 on 2022-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_source_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_industry',
            field=models.CharField(choices=[('', 'Select...'), ('agency', 'Agency'), ('software', 'Software'), ('ecommerce', 'E-commerce'), ('consulting', 'Consulting'), ('education', 'Education'), ('fintech', 'Fintech'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_role',
            field=models.CharField(choices=[('', 'Select...'), ('leadership', 'Leadership'), ('marketing', 'Marketing'), ('business analyst', 'Business Analyst'), ('data scientist', 'Data Scientist'), ('product manager', 'Product Manager'), ('developer', 'Developer'), ('student', 'Student'), ('sales', 'Sales'), ('other', 'Other')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_size',
            field=models.CharField(choices=[('', 'Select...'), ('1', 'Just me'), ('2-10', '2-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-1000', '201-1000'), ('more than 1000', 'More than 1000')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='source_channel',
            field=models.CharField(choices=[('', 'Select...'), ('onlineads', 'Online ad'), ('searchengine', 'Search engine'), ('socialmedia', 'Social media'), ('wordofmouth', 'Recommended by someone'), ('blog', 'Blog or publication'), ('producthunt', 'Product Hunt '), ('other', 'Other')], max_length=32, null=True),
        ),
    ]
