# Generated by Django 4.0.4 on 2022-10-29 07:49

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220505_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(bucket_name='gyana-public', cache_control='public, max-age=31536000', querystring_auth=False), upload_to='profile-pictures/'),
        ),
    ]
