# Generated by Django 3.2.7 on 2021-11-11 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djpaddle.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(null=True)),
                ('passthrough', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('billing_type', models.CharField(choices=[('day', 'day'), ('month', 'month'), ('year', 'year')], max_length=255)),
                ('billing_period', models.IntegerField()),
                ('trial_days', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('cancel_url', models.URLField()),
                ('checkout_id', models.CharField(max_length=64)),
                ('currency', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('event_time', models.DateTimeField()),
                ('marketing_consent', models.BooleanField()),
                ('next_bill_date', models.DateTimeField()),
                ('passthrough', models.TextField()),
                ('quantity', models.IntegerField()),
                ('source', models.URLField()),
                ('status', models.CharField(choices=[('active', 'active'), ('trialing', 'trialing'), ('past_due', 'past due'), ('paused', 'paused'), ('deleted', 'deleted')], max_length=16)),
                ('unit_price', models.FloatField()),
                ('update_url', models.URLField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djpaddle.plan')),
                ('subscriber', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', djpaddle.fields.PaddleCurrencyCodeField(help_text='Three-letter ISO currency code', max_length=3)),
                ('quantity', models.FloatField()),
                ('recurring', models.BooleanField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='djpaddle.plan')),
            ],
            options={
                'ordering': ['currency', 'recurring'],
                'unique_together': {('plan', 'currency', 'recurring')},
            },
        ),
    ]
