# Generated by Django 3.2.5 on 2021-08-06 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0011_auto_20210721_1256"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.integration",
                    ),
                ),
                (
                    "service",
                    models.TextField(
                        help_text="Name of the Fivetran service, uses keys from services.yaml as value",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "fivetran_id",
                    models.TextField(
                        help_text="ID of the connector in Fivetran, crucial to link this Integration to the Fivetran connector",
                        null=True,
                    ),
                ),
                (
                    "schema",
                    models.TextField(
                        help_text="The schema name under which Fivetran saves the data in BigQuery. It also is the name of the schema maintained by Fivetran in their systems.",
                        null=True,
                    ),
                ),
                ("fivetran_authorized", models.BooleanField(default=False)),
                ("fivetran_poll_historical_sync_task_id", models.UUIDField(null=True)),
                ("historical_sync_complete", models.BooleanField(default=False)),
                ("last_synced", models.DateTimeField(null=True)),
            ],
            options={
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
        migrations.RunSQL(
            """
        INSERT INTO connectors_connector
            (integration_id, service, fivetran_id, schema, fivetran_authorized, fivetran_poll_historical_sync_task_id, historical_sync_complete, last_synced, created, updated)
        SELECT id, service, fivetran_id, schema, fivetran_authorized, fivetran_poll_historical_sync_task_id, historical_sync_complete, last_synced, created, updated
        FROM integrations_integration
        where kind = 'fivetran'
        ;
        """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
