# Generated by Django 3.2.5 on 2021-08-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_auto_20210811_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='fivetran_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='connector',
            name='schema',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='connector',
            name='service',
            field=models.TextField(max_length=255),
        ),
    ]
