# Generated by Django 3.2.6 on 2021-09-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_auto_20210811_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='fivetran_succeeded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
