# Generated by Django 3.2.6 on 2021-09-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0005_connector_fivetran_succeeded_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connector',
            options={'ordering': ('-updated',)},
        ),
    ]
