# Generated by Django 3.2.7 on 2021-10-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0006_alter_connector_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='fivetran_sync_started',
            field=models.DateTimeField(null=True),
        ),
    ]
