# Generated by Django 3.2.7 on 2021-11-03 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0007_connector_fivetran_sync_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connector',
            old_name='fivetran_succeeded_at',
            new_name='succeeded_at',
        ),
        migrations.AddField(
            model_name='connector',
            name='config',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='connected_by',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 17, 19, 26, 15784, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='daily_sync_time',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='failed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='group_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='is_historical_sync',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='pause_after_trial',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='paused',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='schedule_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='service_version',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='setup_state',
            field=models.CharField(choices=[('broken', 'Broken'), ('incomplete', 'Incomplete'), ('connected', 'Connected')], default='connected', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='source_sync_details',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='sync_frequency',
            field=models.IntegerField(default=360),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='sync_state',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('syncing', 'Syncing'), ('paused', 'Paused'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='tasks',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='update_state',
            field=models.CharField(choices=[('on_schedule', 'On Schedule'), ('delayed', 'Delayed')], default='on_schedule', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='warnings',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
