# Generated by Django 3.2.7 on 2021-11-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0009_auto_20211103_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='schema_config',
            field=models.JSONField(null=True),
        ),
    ]
