# Generated by Django 3.2.7 on 2021-11-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0010_connector_schema_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='bigquery_succeeded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
