# Generated by Django 3.2.7 on 2021-11-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0011_connector_bigquery_succeeded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="setup_state",
            field=models.CharField(
                choices=[
                    ("broken", "Broken - the connector setup config is broken"),
                    (
                        "incomplete",
                        "Incomplete - the setup config is incomplete, the setup tests never succeeded",
                    ),
                    ("connected", "Connected - the connector is properly set up"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="sync_state",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled - the sync is waiting to be run"),
                    ("syncing", "Syncing - the sync is currently running"),
                    ("paused", "Paused - the sync is currently paused"),
                    (
                        "rescheduled",
                        "Rescheduled - the sync is waiting until more API calls are available in the source service",
                    ),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="update_state",
            field=models.CharField(
                choices=[
                    (
                        "on_schedule",
                        "On Schedule - the sync is running smoothly, no delays",
                    ),
                    (
                        "delayed",
                        "Delayed -  the data is delayed for a longer time than expected for the update",
                    ),
                ],
                max_length=16,
            ),
        ),
    ]
