# Generated by Django 3.2.7 on 2021-11-16 01:13

import os

import requests
from django.db import migrations

FIVETRAN_KEY = os.environ.get("FIVETRAN_KEY")
FIVETRAN_URL = "https://api.fivetran.com/v1"
FIVETRAN_HEADERS = {
    "Authorization": f"Basic {FIVETRAN_KEY}",
    "Accept": "application/json;version=2",
}
MOCK_FIVETRAN = os.environ.get("MOCK_FIVETRAN", "False") == "True"


def update_connectors_to_daily(apps, schema_editor):
    if not MOCK_FIVETRAN:
        Connector = apps.get_model("connectors", "Connector")

        connectors = Connector.objects.all()

        for connector in connectors:
            res = requests.patch(
                f"{FIVETRAN_URL}/connectors/{connector.fivetran_id}",
                json={"sync_frequency": 1440, "daily_sync_time": "00:00"},
                headers=FIVETRAN_HEADERS,
            ).json()

            if res["code"] != "Success":
                print(connector.id)

            return res


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0012_auto_20211105_1018"),
    ]

    operations = [
        migrations.RunPython(
            update_connectors_to_daily, reverse_code=migrations.RunPython.noop
        ),
    ]
