# Generated by Django 3.2.7 on 2021-12-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0013_auto_20211116_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
