# Generated by Django 3.2.7 on 2021-12-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0014_connector_is_scheduled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='is_scheduled',
        ),
    ]
