# Generated by Django 3.2.11 on 2022-02-03 16:08

from django.db import migrations, models

import apps.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0015_remove_connector_is_scheduled"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="basic_reports",
            field=apps.base.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("AD_PERFORMANCE", "AD_PERFORMANCE"),
                        ("ADSET_PERFORMANCE", "ADSET_PERFORMANCE"),
                        ("CAMPAIGN_PERFORMANCE", "CAMPAIGN_PERFORMANCE"),
                    ],
                    max_length=32,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="setup_mode",
            field=models.CharField(
                choices=[("basic", "Basic"), ("advanced", "Advanced")],
                default="advanced",
                max_length=16,
            ),
        ),
    ]
