# Generated by Django 3.2.11 on 2022-02-03 22:05

import apps.base.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0016_auto_20220203_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='basic_reports',
            field=apps.base.fields.ChoiceArrayField(base_field=models.CharField(choices=[('BASIC_AD_PERFORMANCE', 'Ad performance by day: CPC, CPM, CPP, CTR'), ('BASIC_ADSET_PERFORMANCE', 'Ad Set performance by day: CPC, CPM, CPP, CTR'), ('BASIC_CAMPAIGN_PERFORMANCE', 'Campaign performance by day: CPC, CPM, CPP, CTR')], max_length=32), default=list, size=None),
        ),
    ]
