# Generated by Django 3.2.12 on 2022-03-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0017_alter_connector_basic_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='setup_state',
            field=models.CharField(choices=[('broken', 'Broken - the connector setup config is broken'), ('not-found', "Fivetran couldn't find this connector"), ('incomplete', 'Incomplete - the setup config is incomplete, the setup tests never succeeded'), ('connected', 'Connected - the connector is properly set up')], max_length=16),
        ),
    ]
