# Generated by Django 3.2.12 on 2022-04-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0018_alter_connector_setup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='schema',
            field=models.TextField(unique=True),
        ),
    ]
