# Generated by Django 3.2.12 on 2022-04-05 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0019_alter_connector_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='fivetran_id',
            field=models.TextField(default=uuid.uuid4, unique=True),
        ),
    ]
