# Generated by Django 3.2.12 on 2022-05-05 13:14

from django.db import migrations


def forward(apps, schema_editor):
    Connector = apps.get_model("connectors", "Connector")

    google_ads = Connector.objects.filter(service="adwords").all()

    for g in google_ads:
        g.service = "google_ads"

    Connector.objects.bulk_update(google_ads, ["service"])


def backward(apps, schema_editor):
    Connector = apps.get_model("connectors", "Connector")

    google_ads = Connector.objects.filter(service="google_ads").all()

    for g in google_ads:
        g.service = "adwords"

    Connector.objects.bulk_update(google_ads, ["service"])


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0021_alter_connector_sync_state"),
    ]

    operations = [migrations.RunPython(forward, reverse_code=backward)]
