# Generated by Django 4.0.4 on 2022-06-01 12:40

from django.db import migrations, models


def forward(apps, schema_editor):
    Connector = apps.get_model("connectors", "Connector")
    connectors = Connector.objects.all()
    for connector in connectors:
        connector.has_import_triggered = True

    Connector.objects.bulk_update(connectors, ["has_import_triggered"])


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0022_auto_20220505_1314"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="has_import_triggered",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.RunPython(forward, reverse_code=migrations.RunPython.noop),
    ]
