# Generated by Django 4.0.8 on 2023-01-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customreports', '0004_delete_facebookadscustomreport'),
        ('connectors', '0024_alter_connector_has_import_triggered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connector',
        ),
    ]
