# Generated by Django 4.0.8 on 2023-02-02 22:41

import apps.base.clone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file_gcs_path', models.TextField()),
                ('field_delimiter', models.CharField(choices=[('comma', 'Comma'), ('tab', 'Tab'), ('pipe', 'Pipe')], default='comma', max_length=8)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
    ]
