# Generated by Django 4.0.8 on 2024-03-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upload",
            old_name="file_gcs_path",
            new_name="file",
        ),
        migrations.AlterField(
            model_name="upload",
            name="file",
            field=models.FileField(),
        ),
    ]
