# Generated by Django 3.2.5 on 2021-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20210809_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='file',
            new_name='file_gcs_path',
        ),
        migrations.AddField(
            model_name='upload',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
