# Generated by Django 3.2.5 on 2021-08-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20210809_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='has_initial_sync',
        ),
        migrations.AddField(
            model_name='upload',
            name='external_table_sync_started',
            field=models.DateTimeField(null=True),
        ),
    ]
