# Generated by Django 3.2.5 on 2021-08-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20210809_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='external_table_sync_started',
            new_name='sync_started',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='external_table_sync_task_id',
            new_name='sync_task_id',
        ),
    ]
