# Generated by Django 3.2.5 on 2021-08-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20210809_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='last_synced',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='project',
        ),
    ]
