# Generated by Django 3.2.5 on 2021-08-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0016_auto_20210810_1620"),
        ("uploads", "0006_auto_20210810_1619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="integration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="integrations.integration",
            ),
        ),
    ]
