# Generated by Django 3.2.5 on 2021-08-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_alter_upload_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='field_delimiter',
            field=models.CharField(choices=[('comma', 'Comma'), ('tab', 'Tab'), ('pipe', 'Pipe')], default='comma', max_length=8),
            preserve_default=False,
        ),
    ]
