# Generated by Django 3.2.5 on 2021-08-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_upload_field_delimiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='field_delimiter',
            field=models.CharField(choices=[('comma', 'Comma'), ('tab', 'Tab'), ('pipe', 'Pipe')], default='comma', max_length=8),
        ),
    ]
