# Generated by Django 3.2.6 on 2021-09-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_alter_upload_field_delimiter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ('-updated',)},
        ),
    ]
