# Generated by Django 3.2.7 on 2021-12-07 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_alter_upload_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='sync_started',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sync_task_id',
        ),
    ]
