# Generated by Django 3.2.7 on 2021-12-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboards', '0016_alter_dashboard_shared_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(default='date_range', max_length=16)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('date_range', models.CharField(blank=True, choices=[('today', 'today'), ('tomorrow', 'tomorrow'), ('yesterday', 'yesterday'), ('oneweekago', 'one week ago'), ('onemonthago', 'one month ago'), ('oneyearago', 'one year ago'), ('thisweek', 'This week (starts Monday)'), ('thisweekuptodate', 'This week (starts Monday) up to date'), ('lastweek', 'Last week (starts Monday)'), ('last7', 'Last 7 days'), ('last14', 'Last 14 days'), ('last28', 'Last 28 days'), ('thismonth', 'This month'), ('thismonthuptodate', 'This month to date'), ('lastmonth', 'Last month'), ('last30', 'Last 30 days'), ('last90', 'Last 90 days'), ('thisquarter', 'This quarter'), ('thisquarteruptodate', 'This quarter up to date'), ('lastquarter', 'Last quarter'), ('last180', 'Last 180 days'), ('last12month', 'Last 12 months'), ('lastyear', 'Last calendar year'), ('thisyear', 'This year'), ('thisyearuptodate', 'This year (January - up to date)'), ('custom', 'Custom')], default='thisyear', max_length=20)),
                ('dashboard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboards.dashboard')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
    ]
