# Generated by Django 4.0.8 on 2023-02-02 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('widgets', '0001_initial'),
        ('dashboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcontrolwidget',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontrolwidget',
            name='page',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboards.page'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='page',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboards.page'),
        ),
        migrations.AddField(
            model_name='historicalcontrol',
            name='widget',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='widgets.widget'),
        ),
        migrations.AddField(
            model_name='controlwidget',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='controls.control'),
        ),
        migrations.AddField(
            model_name='controlwidget',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_widgets', to='dashboards.page'),
        ),
        migrations.AddField(
            model_name='control',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboards.page'),
        ),
        migrations.AddField(
            model_name='control',
            name='widget',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='widgets.widget'),
        ),
    ]
