# Generated by Django 3.2.7 on 2021-12-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_page'),
        ('controls', '0002_auto_20211214_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboards.page'),
        ),
        migrations.CreateModel(
            name='ControlWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x', models.IntegerField(default=0, help_text='The x field is in absolute pixel value.')),
                ('y', models.IntegerField(default=0, help_text='The y field is in absolute pixel value.')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_widgets', to='controls.control')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_widgets', to='dashboards.page')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
        ),
    ]
