# Generated by Django 3.2.7 on 2021-12-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_auto_20211215_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlwidget',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='controls.control'),
        ),
    ]
