# Generated by Django 3.2.12 on 2022-03-14 11:58

from django.db import migrations
from django.db.models import F


def forward(apps, schema_editor):
    ControlWidget = apps.get_model("controls", "ControlWidget")
    to_update = ControlWidget.objects.exclude(page=F("control__page")).all()
    for control_widget in to_update:
        if hasattr(control_widget.page, "control"):
            control_widget.control = control_widget.page.control
        else:
            control = control_widget.control
            control.pk = None
            control.page = control_widget.page
            control.save()
            control_widget.control = control
    ControlWidget.objects.bulk_update(to_update, ["control"])


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0007_auto_20220309_1346"),
    ]

    operations = [migrations.RunPython(forward, reverse_code=migrations.RunPython.noop)]
