# Generated by Django 3.2 on 2021-05-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflows', '0004_alter_node_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('input', 'Input')], max_length=16),
        ),
    ]
