# Generated by Django 3.2 on 2021-05-04 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0004_auto_20210503_0008"),
        ("dataflows", "0005_alter_node_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="config",
        ),
        migrations.AddField(
            model_name="node",
            name="_input_dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="datasets.dataset",
            ),
        ),
    ]
