# Generated by Django 3.2 on 2021-05-04 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("dataflows", "0006_auto_20210504_2105"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataflow",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
