# Generated by Django 3.2 on 2021-05-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataflows', '0010_auto_20210505_1432'),
        ('dataflows', '0010_auto_20210506_1614'),
    ]

    operations = [
    ]
