# Generated by Django 3.2 on 2021-05-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataflows", "0011_merge_0010_auto_20210505_1432_0010_auto_20210506_1614"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Aggregations",
            new_name="Aggregation",
        ),
        migrations.RenameModel(
            old_name="Groups",
            new_name="Group",
        ),
        migrations.AlterField(
            model_name="node",
            name="kind",
            field=models.CharField(
                choices=[
                    ("input", "Input"),
                    ("select", "Select"),
                    ("join", "Join"),
                    ("group", "Group"),
                ],
                max_length=16,
            ),
        ),
    ]
