# Generated by Django 3.2 on 2021-05-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dataflows", "0013_auto_20210507_0211"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="output_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="functioncolumn",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aggregations",
                to="dataflows.node",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="kind",
            field=models.CharField(
                choices=[
                    ("input", "Input"),
                    ("output", "Output"),
                    ("select", "Select"),
                    ("join", "Join"),
                    ("group", "Group"),
                ],
                max_length=16,
            ),
        ),
    ]
