# Generated by Django 3.2 on 2021-05-08 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
        ('dataflows', '0014_auto_20210507_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='dataflow',
        ),
        migrations.AlterField(
            model_name='node',
            name='input_dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
    ]
