# Generated by Django 4.0.8 on 2023-02-02 22:41

import apps.base.clone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Untitled', max_length=255)),
                ('state', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending'), ('running', 'Running'), ('failed', 'Failed'), ('success', 'Success')], default='incomplete', max_length=16)),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('last_success_run', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_last_success_run_for', to='runs.jobrun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ('-updated',),
                'abstract': False,
            },
            bases=(apps.base.clone.CloneMixin, models.Model),
        ),
    ]
