# Generated by Django 3.2 on 2021-05-10 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("last_run", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="FunctionColumn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "function",
                    models.CharField(
                        choices=[("sum", "Sum"), ("count", "Count")], max_length=20
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("input", "Input"),
                            ("output", "Output"),
                            ("select", "Select"),
                            ("join", "Join"),
                            ("group", "Group"),
                        ],
                        max_length=16,
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("output_name", models.CharField(max_length=100, null=True)),
                (
                    "join_how",
                    models.CharField(
                        choices=[
                            ("inner", "Inner"),
                            ("outer", "Outer"),
                            ("left", "Left"),
                            ("right", "Right"),
                        ],
                        default="inner",
                        max_length=12,
                    ),
                ),
                ("join_left", models.CharField(blank=True, max_length=300, null=True)),
                ("join_right", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflows.workflow",
                    ),
                ),
            ],
        ),
    ]
