# Generated by Django 3.2 on 2021-05-10 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workflows", "0001_initial"),
        ("tables", "0001_initial"),
        ("projects", "0002_project_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="input_table",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tables.table",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="parents",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="workflows.Node"
            ),
        ),
        migrations.AddField(
            model_name="functioncolumn",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aggregations",
                to="workflows.node",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="column",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="workflows.node",
            ),
        ),
    ]
