# Generated by Django 3.2 on 2021-05-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functioncolumn',
            name='function',
            field=models.CharField(choices=[('sum', 'Sum'), ('count', 'Count'), ('average', 'Average')], max_length=20),
        ),
    ]
