# Generated by Django 3.2 on 2021-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0003_alter_functioncolumn_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functioncolumn",
            name="function",
            field=models.CharField(
                choices=[("sum", "Sum"), ("count", "Count"), ("mean", "Average")],
                max_length=20,
            ),
        ),
    ]
