# Generated by Django 3.2 on 2021-05-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_auto_20210513_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('select', 'Select'), ('join', 'Join'), ('group', 'Group'), ('union', 'Union'), ('sort', 'Sort'), ('limit', 'Limit'), ('filter', 'Filter')], max_length=16),
        ),
    ]
