# Generated by Django 3.2 on 2021-05-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_alter_node_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='error',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
