# Generated by Django 3.2 on 2021-05-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_node_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflow'),
        ),
    ]
