# Generated by Django 3.2 on 2021-05-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_alter_node_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functioncolumn',
            name='function',
            field=models.CharField(choices=[('sum', 'Sum'), ('count', 'Count'), ('mean', 'Average'), ('max', 'Maximum'), ('min', 'Minimum'), ('std', 'Standard deviation')], max_length=20),
        ),
    ]
