# Generated by Django 3.2 on 2021-05-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_auto_20210526_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('select', 'Select'), ('join', 'Join'), ('aggregation', 'Aggregation'), ('union', 'Union'), ('sort', 'Sort'), ('limit', 'Limit'), ('filter', 'Filter'), ('edit', 'Edit'), ('add', 'Add')], max_length=16),
        ),
        migrations.CreateModel(
            name='AddColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('function', models.CharField(choices=[('lower', 'to lowercase'), ('upper', 'to uppercase'), ('isnull', 'is null'), ('cummax', 'cummulative max'), ('cummin', 'cummulative min'), ('abs', 'absolute value'), ('sqrt', 'square root')], max_length=20)),
                ('label', models.CharField(max_length=300)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_columns', to='workflows.node')),
            ],
        ),
    ]
