# Generated by Django 3.2 on 2021-05-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0015_auto_20210526_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcolumn',
            name='function',
        ),
        migrations.AddField(
            model_name='addcolumn',
            name='integer_function',
            field=models.CharField(choices=[('lower', 'to lowercase'), ('upper', 'to uppercase'), ('isnull', 'is null'), ('cummax', 'cummulative max'), ('cummin', 'cummulative min'), ('abs', 'absolute value'), ('sqrt', 'square root')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addcolumn',
            name='string_function',
            field=models.CharField(choices=[('lower', 'to lowercase'), ('upper', 'to uppercase'), ('isnull', 'is null'), ('cummax', 'cummulative max'), ('cummin', 'cummulative min'), ('abs', 'absolute value'), ('sqrt', 'square root')], max_length=20, null=True),
        ),
    ]
