# Generated by Django 3.2 on 2021-05-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0016_auto_20210527_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcolumn',
            name='integer_function',
            field=models.CharField(choices=[('isnull', 'is null'), ('cummax', 'cummulative max'), ('cummin', 'cummulative min'), ('abs', 'absolute value'), ('sqrt', 'square root')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='string_function',
            field=models.CharField(choices=[('lower', 'to lowercase'), ('upper', 'to uppercase'), ('isnull', 'is null')], max_length=20, null=True),
        ),
    ]
