# Generated by Django 3.2 on 2021-06-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0017_auto_20210531_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editcolumn',
            name='function',
        ),
        migrations.AddField(
            model_name='editcolumn',
            name='integer_function',
            field=models.CharField(choices=[('isnull', 'is null'), ('cummax', 'cummulative max'), ('cummin', 'cummulative min'), ('abs', 'absolute value'), ('sqrt', 'square root')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='editcolumn',
            name='string_function',
            field=models.CharField(choices=[('lower', 'to lowercase'), ('upper', 'to uppercase'), ('isnull', 'is null')], max_length=20, null=True),
        ),
    ]
