# Generated by Django 3.2 on 2021-06-03 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0018_auto_20210601_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcolumn',
            old_name='name',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='name',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='editcolumn',
            old_name='name',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='functioncolumn',
            old_name='name',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='renamecolumn',
            old_name='name',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='sortcolumn',
            old_name='name',
            new_name='column',
        ),
    ]
