# Generated by Django 3.2 on 2021-06-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0020_auto_20210608_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
