# Generated by Django 3.2 on 2021-06-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0022_node_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="addcolumn",
            name="date_function",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("year", "year"),
                    ("month", "month"),
                    ("day", "day"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="addcolumn",
            name="datetime_function",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("hour", "hour"),
                    ("minute", "minute"),
                    ("second", "second"),
                    ("millisecond", "millisecond"),
                    ("year", "year"),
                    ("month", "month"),
                    ("day", "day"),
                    ("epoch_seconds", "epoch seconds"),
                    ("time", "Time"),
                    ("date", "Date"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="addcolumn",
            name="time_function",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("hour", "hour"),
                    ("minute", "minute"),
                    ("second", "second"),
                    ("millisecond", "millisecond"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="editcolumn",
            name="date_function",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("year", "year"),
                    ("month", "month"),
                    ("day", "day"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="editcolumn",
            name="datetime_function",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("hour", "hour"),
                    ("minute", "minute"),
                    ("second", "second"),
                    ("millisecond", "millisecond"),
                    ("year", "year"),
                    ("month", "month"),
                    ("day", "day"),
                    ("epoch_seconds", "epoch seconds"),
                    ("time", "Time"),
                    ("date", "Date"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="editcolumn",
            name="time_function",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("hour", "hour"),
                    ("minute", "minute"),
                    ("second", "second"),
                    ("millisecond", "millisecond"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="addcolumn",
            name="integer_function",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("cummax", "cummulative max"),
                    ("cummin", "cummulative min"),
                    ("abs", "absolute value"),
                    ("sqrt", "square root"),
                    ("ceil", "ceiling"),
                    ("floor", "floor"),
                    ("ln", "ln"),
                    ("log2", "log2"),
                    ("log10", "log10"),
                    ("exp", "exp"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="addcolumn",
            name="string_function",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("lower", "to lowercase"),
                    ("upper", "to uppercase"),
                    ("length", "length"),
                    ("reverse", "reverse"),
                    ("strip", "strip"),
                    ("lstrip", "lstrip"),
                    ("rstrip", "rstrip"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="editcolumn",
            name="integer_function",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("cummax", "cummulative max"),
                    ("cummin", "cummulative min"),
                    ("abs", "absolute value"),
                    ("sqrt", "square root"),
                    ("ceil", "ceiling"),
                    ("floor", "floor"),
                    ("ln", "ln"),
                    ("log2", "log2"),
                    ("log10", "log10"),
                    ("exp", "exp"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="editcolumn",
            name="string_function",
            field=models.CharField(
                choices=[
                    ("isnull", "is empty"),
                    ("notnull", "is not empty"),
                    ("lower", "to lowercase"),
                    ("upper", "to uppercase"),
                    ("length", "length"),
                    ("reverse", "reverse"),
                    ("strip", "strip"),
                    ("lstrip", "lstrip"),
                    ("rstrip", "rstrip"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
