# Generated by Django 3.2 on 2021-06-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_auto_20210615_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcolumn',
            name='float_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addcolumn',
            name='integer_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addcolumn',
            name='string_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editcolumn',
            name='float_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editcolumn',
            name='integer_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editcolumn',
            name='string_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='date_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('year', 'year'), ('month', 'month'), ('day', 'day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='datetime_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('hour', 'hour'), ('minute', 'minute'), ('second', 'second'), ('millisecond', 'millisecond'), ('year', 'year'), ('month', 'month'), ('day', 'day'), ('epoch_seconds', 'epoch seconds'), ('time', 'time'), ('date', 'date')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='integer_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('cummax', 'cummax'), ('cummin', 'cummin'), ('abs', 'absolute value'), ('sqrt', 'square root'), ('ceil', 'ceiling'), ('floor', 'floor'), ('ln', 'ln'), ('log2', 'log2'), ('log10', 'log10'), ('log', 'log'), ('exp', 'exponent'), ('add', 'add'), ('sub', 'subtract'), ('mul', 'multiply'), ('div', 'divide')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='string_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('lower', 'to lowercase'), ('upper', 'to uppercase'), ('length', 'length'), ('reverse', 'reverse'), ('strip', 'strip'), ('lstrip', 'lstrip'), ('rstrip', 'rstrip'), ('like', 'like'), ('contains', 'contains'), ('left', 'left'), ('right', 'right'), ('repeat', 'repeat')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addcolumn',
            name='time_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('hour', 'hour'), ('minute', 'minute'), ('second', 'second'), ('millisecond', 'millisecond')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='date_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('year', 'year'), ('month', 'month'), ('day', 'day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='datetime_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('hour', 'hour'), ('minute', 'minute'), ('second', 'second'), ('millisecond', 'millisecond'), ('year', 'year'), ('month', 'month'), ('day', 'day'), ('epoch_seconds', 'epoch seconds'), ('time', 'time'), ('date', 'date')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='integer_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('cummax', 'cummax'), ('cummin', 'cummin'), ('abs', 'absolute value'), ('sqrt', 'square root'), ('ceil', 'ceiling'), ('floor', 'floor'), ('ln', 'ln'), ('log2', 'log2'), ('log10', 'log10'), ('log', 'log'), ('exp', 'exponent'), ('add', 'add'), ('sub', 'subtract'), ('mul', 'multiply'), ('div', 'divide')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='string_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('lower', 'to lowercase'), ('upper', 'to uppercase'), ('length', 'length'), ('reverse', 'reverse'), ('strip', 'strip'), ('lstrip', 'lstrip'), ('rstrip', 'rstrip'), ('like', 'like'), ('contains', 'contains'), ('left', 'left'), ('right', 'right'), ('repeat', 'repeat')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='editcolumn',
            name='time_function',
            field=models.CharField(choices=[('isnull', 'is empty'), ('notnull', 'is not empty'), ('fillna', 'fill empty values'), ('hour', 'hour'), ('minute', 'minute'), ('second', 'second'), ('millisecond', 'millisecond')], max_length=20, null=True),
        ),
    ]
