# Generated by Django 3.2 on 2021-06-17 09:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0025_alter_node_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('select', 'Select'), ('join', 'Join'), ('aggregation', 'Aggregation'), ('union', 'Union'), ('sort', 'Sort'), ('limit', 'Limit'), ('filter', 'Filter'), ('edit', 'Edit'), ('add', 'Add'), ('rename', 'Rename'), ('text', 'Text'), ('formula', 'Formula'), ('distinct', 'Distinct')], max_length=16),
        ),
        migrations.CreateModel(
            name='FormulaColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField(blank=True, null=True)),
                ('label', models.CharField(max_length=300, validators=[django.core.validators.RegexValidator('^[a-zA-Z_][0-9a-zA-Z_]*$', 'Only numbers, letters and underscores allowed.')])),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_columns', to='workflows.node')),
            ],
        ),
    ]
