# Generated by Django 3.2 on 2021-06-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_table_source'),
        ('workflows', '0026_auto_20210617_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='pivot_aggregation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='pivot_column',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='pivot_index',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='pivot_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pivot_table', to='tables.table'),
        ),
        migrations.AddField(
            model_name='node',
            name='pivot_value',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('select', 'Select'), ('join', 'Join'), ('aggregation', 'Aggregation'), ('union', 'Union'), ('sort', 'Sort'), ('limit', 'Limit'), ('filter', 'Filter'), ('edit', 'Edit'), ('add', 'Add'), ('rename', 'Rename'), ('text', 'Text'), ('formula', 'Formula'), ('distinct', 'Distinct'), ('pivot', 'Pivot')], max_length=16),
        ),
    ]
