# Generated by Django 3.2 on 2021-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0028_auto_20210622_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
