# Generated by Django 3.2 on 2021-06-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0029_alter_node_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='pivot_aggregation',
            field=models.CharField(blank=True, choices=[('sum', 'Sum'), ('count', 'Count'), ('mean', 'Average'), ('max', 'Maximum'), ('min', 'Minimum'), ('std', 'Standard deviation')], max_length=20, null=True),
        ),
    ]
