# Generated by Django 3.2 on 2021-06-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0030_alter_node_pivot_aggregation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='updated',
            new_name='data_updated',
        ),
    ]
