# Generated by Django 3.2 on 2021-06-25 09:51

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20210625_0951'),
        ('workflows', '0031_rename_updated_node_data_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='pivot_table',
        ),
        migrations.AddField(
            model_name='node',
            name='intermediate_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_table', to='tables.table'),
        ),
        migrations.AddField(
            model_name='node',
            name='unpivot_column',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='unpivot_value',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('select', 'Select'), ('join', 'Join'), ('aggregation', 'Aggregation'), ('union', 'Union'), ('sort', 'Sort'), ('limit', 'Limit'), ('filter', 'Filter'), ('edit', 'Edit'), ('add', 'Add'), ('rename', 'Rename'), ('text', 'Text'), ('formula', 'Formula'), ('distinct', 'Distinct'), ('pivot', 'Pivot'), ('unpivot', 'Unpivot')], max_length=16),
        ),
        migrations.CreateModel(
            name='SecondaryColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=300)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_columns', to='workflows.node')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
