# Generated by Django 3.2 on 2021-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0032_auto_20210625_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='data_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
