# Generated by Django 3.2 on 2021-07-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0033_alter_node_data_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='select_mode',
            field=models.CharField(choices=[('keep', 'keep'), ('exclude', 'exclude')], default='keep', max_length=8),
        ),
    ]
