# Generated by Django 3.2 on 2021-07-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0035_node_union_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='kind',
            field=models.CharField(choices=[('input', 'Get data'), ('output', 'Save data'), ('select', 'Select'), ('join', 'Join'), ('aggregation', 'Aggregation'), ('union', 'Union'), ('sort', 'Sort'), ('limit', 'Limit'), ('filter', 'Filter'), ('edit', 'Edit'), ('add', 'Add'), ('rename', 'Rename'), ('text', 'Text'), ('formula', 'Formula'), ('distinct', 'Distinct'), ('pivot', 'Pivot'), ('unpivot', 'Unpivot'), ('intersect', 'Intersection')], max_length=16),
        ),
    ]
