# Generated by Django 3.2 on 2021-07-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filters", "0017_alter_filter_node"),
        ("tables", "0007_auto_20210713_2233"),
        ("workflows", "0042_auto_20210713_2142"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="column",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="editcolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="formulacolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="functioncolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="node",
                    name="input_table",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="node",
                    name="intermediate_table",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="node",
                    name="parents",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="node",
                    name="workflow",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="renamecolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="secondarycolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="sortcolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="windowcolumn",
                    name="node",
                )
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="AddColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(name="AddColumn", table="nodes_addcolumn")
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Column",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(name="Column", table="nodes_column")
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="EditColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(name="EditColumn", table="nodes_editcolumn")
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="FormulaColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="FormulaColumn", table="nodes_formulacolumn"
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="FunctionColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="FunctionColumn", table="nodes_functioncolumn"
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Node",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(name="Node", table="nodes_node"),
                migrations.RunSQL(
                    sql="ALTER TABLE workflows_node_parents RENAME TO nodes_node_parents",
                    reverse_sql="ALTER TABLE nodes_node_parents RENAME TO workflows_node_parents",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="RenameColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="RenameColumn", table="nodes_renamecolumn"
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="SecondaryColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="SecondaryColumn", table="nodes_secondarycolumn"
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="SortColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(name="SortColumn", table="nodes_sortcolumn")
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="WindowColumn",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="WindowColumn", table="nodes_windowcolumn"
                )
            ],
        ),
    ]
