# Generated by Django 3.2.7 on 2021-12-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0044_alter_workflow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='failed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='succeeded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
