# Generated by Django 3.2.7 on 2021-12-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0045_auto_20211203_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='state',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('running', 'Running'), ('failed', 'Failed'), ('success', 'Success')], default='incomplete', max_length=16),
        ),
    ]
