# Generated by Django 3.2.7 on 2021-12-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0002_jobrun_user"),
        ("workflows", "0047_auto_20211209_0252"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="last_run",
        ),
        migrations.AddField(
            model_name="workflow",
            name="last_success_run",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_last_success_run_for",
                to="runs.jobrun",
            ),
        ),
    ]
