# Generated by Django 3.2.7 on 2021-12-13 22:25

from django.db import migrations, models


class State(models.TextChoices):
    PENDING = "pending", "Pending"
    RUNNING = "running", "Running"
    FAILED = "failed", "Failed"
    SUCCESS = "success", "Success"


def forwards(apps, schema_editor):
    Workflow = apps.get_model("workflows", "Workflow")

    for workflow in Workflow.objects.iterator():
        workflow.last_success_run = (
            workflow.runs.filter(state=State.SUCCESS).order_by("-started_at").first()
        )
        workflow.save(update_fields=["last_success_run"])


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0048_auto_20211213_2225"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
