# Generated by Django 3.2.7 on 2021-12-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0049_auto_20211213_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='failed_at',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='succeeded_at',
        ),
    ]
