# Generated by Django 3.2.7 on 2021-12-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0050_auto_20211214_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='state',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending'), ('running', 'Running'), ('failed', 'Failed'), ('success', 'Success')], default='incomplete', max_length=16),
        ),
    ]
