# Generated by Django 4.0.8 on 2023-03-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_wagtail_waffle_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='last_checkout',
        ),
    ]
