# Generated by Django 4.0.8 on 2025-01-30 22:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_credittransaction_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='icon',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='team-icons/'),
        ),
    ]
