# Generated by Django 3.2 on 2021-07-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20210705_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
