# Generated by Django 3.2 on 2021-07-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_delete_invitation"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='team',
        #     name='subscription',
        # ),
    ]
