# Generated by Django 3.2 on 2021-07-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_team_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
