# Generated by Django 3.2 on 2021-07-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_team_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
