# Generated by Django 3.2.5 on 2021-08-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20210713_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='row_limit',
            field=models.BigIntegerField(default=1000000),
        ),
    ]
