# Generated by Django 3.2.5 on 2021-08-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20210820_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='enabled',
        ),
    ]
