# Generated by Django 3.2.5 on 2021-08-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_remove_team_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='row_limit',
        ),
    ]
