# Generated by Django 3.2.6 on 2021-09-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_team_override_row_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='override_row_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
