# Generated by Django 3.2.6 on 2021-09-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_alter_team_override_row_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-updated',)},
        ),
    ]
