# Generated by Django 3.2.7 on 2021-09-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20210921_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='team-icons/'),
        ),
    ]
