# Generated by Django 3.2.7 on 2021-10-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_creditstatement_credittransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-created',)},
        ),
    ]
