# Generated by Django 3.2.7 on 2021-10-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0019_alter_team_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="deleted",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
