# Generated by Django 3.2.7 on 2021-10-28 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djpaddle', '0004_auto_20210119_0436'),
        ('teams', '0020_team_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djpaddle.subscription'),
        ),
    ]
