# Generated by Django 3.2.7 on 2021-10-28 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djpaddle", "0001_initial"),
        ("teams", "0020_team_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="subscription",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djpaddle.subscription",
            ),
        ),
    ]
