# Generated by Django 3.2.7 on 2021-11-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_team_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='subscription',
        ),
    ]
