# Generated by Django 3.2.7 on 2021-11-11 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djpaddle', '0002_alter_subscription_subscriber'),
        ('teams', '0022_remove_team_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_checkout',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djpaddle.checkout'),
        ),
    ]
