# Generated by Django 3.2.7 on 2021-11-15 13:41

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0024_team_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='GMT'),
        ),
    ]
