# Generated by Django 3.2.11 on 2022-01-17 22:53

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration for issue: cannot truncate a table referenced in a foreign key constraint: Table "waffle_flag_groups" references "auth_group".
    See more: https://github.com/django-waffle/django-waffle/issues/317
    Extended for Wagtail: https://github.com/wagtail/wagtail/issues/1824
    """

    dependencies = [
        ("teams", "0026_flag"),
        ("wagtailsearch", "0003_remove_editors_pick"),
        ("waffle", "__latest__"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS waffle_flag_groups",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS waffle_flag_users", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS wagtailsearch_editorspick CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
