# Generated by Django 3.2.11 on 2022-02-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0027_auto_20220117_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='override_credit_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
