# Generated by Django 3.2.11 on 2022-02-21 10:18

import apps.teams.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0029_team_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.CharField(default=apps.teams.utils.getRandomColor, max_length=7),
        ),
    ]
