# Generated by Django 3.2.12 on 2022-05-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0030_alter_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='has_free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
