# Generated by Django 3.2.13 on 2022-05-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0031_team_has_free_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
