# Generated by Django 3.2.13 on 2022-05-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0032_team_deleted_by_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='override_rows_per_integration_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
