# Generated by Django 4.0.8 on 2022-12-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0034_alter_team_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
